'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations = {
  en: {
    'dashboard': 'Dashboard',
    'academics': 'Academics',
    'students': 'Students',
    'exams': 'Assessments',
    'schedule': 'Schedule',
    'attendance': 'Attendance',
    'visitors': 'Visitors',
    'inventory': 'Inventory',
    'fees': 'Fees & Payments',
    'hr': 'HR',
    'transport': 'Transport',
    'analytics': 'Analytics',
    'communication': 'Communication',
    'settings': 'Settings',
    'notifications': 'Notifications',
    'switch_language': 'Switch Language',
    'toggle_theme': 'Toggle Theme',
    'sign_out': 'Sign Out',
    'search': 'Search...',
    'welcome': 'Welcome back',
    'close_profile': 'Close Profile',
    'view_all_notifications': 'View All Notifications',
    'new': 'New',
    'add': 'Add',
    'edit': 'Edit',
    'delete': 'Delete',
    'save': 'Save',
    'cancel': 'Cancel',
    'actions': 'Actions',
    'status': 'Status',
    'name': 'Name',
    'date': 'Date',
    'description': 'Description',
    'category': 'Category',
    'active': 'Active',
    'inactive': 'Inactive',
    'upcoming': 'Upcoming',
    'overview': 'Overview',
    'academic_years': 'Academic Years',
    'classes': 'Classes',
    'subjects': 'Subjects',
    'manage': 'Manage',
    'total': 'Total',
    'view': 'View',
    'loading': 'Loading...',
    'no_data': 'No data found',
    'success': 'Success',
    'error': 'Error',
    'confirm_delete': 'Are you sure you want to delete this?',
    'inventory_desc': 'Manage school assets and equipment.',
    'visitors_desc': 'Manage campus visitors and check-ins.',
    'academics_desc': 'Manage academic years, classes, and subjects.',
    'student_id': 'Student ID',
    'grade': 'Grade',
    'section': 'Section',
    'phone': 'Phone',
    'email': 'Email',
    'address': 'Address',
    'parent_name': 'Parent Name',
    'relation': 'Relation',
    'purpose': 'Purpose',
    'host': 'Host',
    'time_in': 'Time In',
    'time_out': 'Time Out',
    'check_in': 'Check In',
    'check_out': 'Check Out',
    'asset_name': 'Asset Name',
    'assigned_to': 'Assigned To',
    'maintenance': 'Maintenance',
    'asset': 'Asset',
    'none': 'None',
    'account': 'Account',
    'profile': 'Profile',
    'no_notifications': 'No new notifications',
    'across_all_grades': 'Across all grades',
    'active_curriculum': 'Active curriculum',
    'no_permission': 'You do not have permission to view this page.',
    'welcome_back': 'Welcome back',
    'school_status_desc': 'Here is what\'s happening with your school today.',
    'total_students': 'Total Students',
    'attendance_today': 'Attendance Today',
    'fees_collected': 'Fees Collected',
    'pending_dues': 'Pending Dues',
    'recent_activity': 'Recent Activity',
    'quick_actions': 'Quick Actions',
    'register_student': 'Register Student',
    'manage_fees': 'Manage Fees',
    'urgent_alerts': 'Urgent Alerts',
    'no_urgent_alerts': 'No urgent alerts.',
    'hello': 'Hello',
    'classes_today': 'You have {count} classes today.',
    'take_attendance': 'Take Attendance',
    'attendance_rate': 'Attendance Rate',
    'upcoming_tasks': 'Upcoming Tasks',
    'todays_schedule': 'Today\'s Schedule',
    'view_full_schedule': 'View Full Schedule',
    'mark_attendance': 'Mark Attendance',
    'post_notice': 'Post Notice',
    'add_assessment': 'Add Assessment',
    'recent_notices': 'Recent Notices',
    'no_recent_notices': 'No recent notices.',
    'financial_overview': 'Financial overview for today.',
    'collected_today': 'Collected Today',
    'pending_fees': 'Pending Fees',
    'record_payment': 'Record New Payment',
    'latest_update_child': 'Here is the latest update for your child.',
    'student_profile': 'Student Profile',
    'upcoming_assignments': 'Upcoming Assignments',
    'due': 'Due',
    'posted': 'Posted',
    'by': 'by',
    'students_directory': 'Students Directory',
    'students_directory_desc': 'Find contact information and detailed profiles for students and parents.',
    'add_student': 'Add Student',
    'directory': 'Directory',
    'history': 'History',
    'promotions': 'Promotions',
    'filters': 'Filters',
    'search_students': 'Search students...',
    'student': 'Student',
    'roll_number': 'Roll Number',
    'parent_guardian': 'Parent/Guardian',
    'no_students_found': 'No students found.',
    'previous': 'Previous',
    'next': 'Next',
    'page_of': 'Page {page} of {total}',
    'dropped_deleted_students': 'Dropped & Deleted Students',
    'search_history': 'Search history...',
    'reason': 'Reason',
    'restore': 'Restore',
    'student_promotions': 'Student Promotions',
    'student_promotions_desc': 'Promote students to the next grade or academic year.',
    'promote_by_grade': 'Promote by Grade',
    'promote_by_grade_desc': 'Bulk promote all students in a specific grade to the next level.',
    'start_promotion': 'Start Promotion',
    'promote_by_class': 'Promote by Class',
    'promote_by_class_desc': 'Promote students from a specific class section.',
    'manual_promotion': 'Manual Promotion',
    'manual_promotion_desc': 'Select individual students to promote manually.',
    'promote_students': 'Promote Students',
    'promote_students_grade_desc': 'Promote students by grade level',
    'promote_students_class_desc': 'Promote students by class section',
    'promote_students_manual_desc': 'Manually select students to promote',
    'select_current_grade': 'Select Current Grade',
    'select_current_class': 'Select Current Class',
    'search_student': 'Search Student',
    'search_student_placeholder': 'Search student name or ID...',
    'target_grade': 'Target Grade (Promotion To)',
    'select_target_grade': 'Select Target Grade',
    'graduated_completed': 'Graduated / Completed',
    'promotion_warning': 'Promoting students will update their current grade and academic year. This action will also create a new enrollment record for the upcoming session.',
    'academic_years': 'Academic Years',
    'classes_sections': 'Classes & Sections',
    'curriculum_subjects': 'Curriculum Subjects',
    'add_year': 'Add Year',
    'add_class': 'Add Class',
    'add_subject': 'Add Subject',
    'edit_year': 'Edit Academic Year',
    'edit_class': 'Edit Class',
    'edit_subject': 'Edit Subject',
    'year_name': 'Year Name',
    'start_date': 'Start Date',
    'end_date': 'End Date',
    'grade': 'Grade',
    'section': 'Section',
    'subject_name': 'Subject Name',
    'subject_code': 'Subject Code',
    'description': 'Description',
    'assessments': 'Assessments',
    'gradebook': 'Gradebook',
    'submissions': 'Submissions',
    'all_assessments': 'All Assessments',
    'new_assessment': 'New Assessment',
    'assessment_title': 'Assessment Title',
    'max_score': 'Max Score',
    'due_date': 'Due Date',
    'view_submissions': 'View Submissions',
    'grade_now': 'Grade Now',
    'select_class': 'Select Class',
    'select_subject': 'Select Subject',
    'select_assessment_to_grade': 'Select Assessment to Grade',
    'save_grades': 'Save Grades',
    'student_name': 'Student Name',
    'score': 'Score',
    'feedback': 'Feedback',
    'status': 'Status',
    'roll': 'Roll',
    'back_to_list': 'Back to List',
    'instructions': 'Instructions',
    'homework': 'Homework',
    'assignment': 'Assignment',
    'online_exam': 'Online Exam',
    'offline_exam': 'Offline Exam',
    'exam_date': 'Exam Date',
    'grading': 'Grading',
    'remember_to_save': 'Remember to save before leaving',
    'my_assignments': 'My Assignments',
    'past_results': 'Past Results',
    'current_gpa': 'Current GPA',
    'top_class': 'Top 10% of Class',
    'total_credits': 'Total Credits',
    'absences': 'Absences',
    'subject_breakdown': 'Subject Breakdown',
    'term_1': 'Term 1',
    'todo': 'To Do',
    'in_progress': 'In Progress',
    'completed': 'Completed',
    'academic_report': 'Academic Report',
    'viewing_performance_for': 'Viewing performance for',
    'update_academic_year_desc': 'Update academic year details.',
    'create_academic_year_desc': 'Create a new academic year period.',
    'update_class_desc': 'Update class details.',
    'create_class_desc': 'Create a new class section.',
    'update_subject_desc': 'Update subject details.',
    'create_subject_desc': 'Create a new subject for the curriculum.',
    'attendance_history': 'Attendance History',
    'attendance_history_desc': 'Review past attendance records for your classes.',
    'back_to_marking': 'Back to Marking',
    'no_history_found': 'No attendance history found.',
    'students_marked': 'Students Marked',
    'mark_attendance': 'Mark Attendance',
    'no_students_attendance_desc': 'There are no students registered for the current academic year. Please add students first.',
    'register_student': 'Register New Student',
    'marked': 'Marked',
    'please_mark_all': 'Please mark all students',
    'saved_successfully': 'Saved Successfully',
    'submit_attendance': 'Submit Attendance',
    'attendance_record': 'Attendance Record',
    'viewing_records_for': 'Viewing records for',
    'your_student': 'your student',
    'recent_activity': 'Recent Activity',
    'no_records_found': 'No attendance records found.',
    'present': 'Present',
    'absent': 'Absent',
    'late': 'Late',
    'excused': 'Excused',
    'school_attendance': 'School Attendance',
    'view_history': 'View History',
    'overall_attendance_for': 'Overall Attendance for',
    'students': 'Students',
    'late_arrivals': 'Late Arrivals',
    'absences': 'Absences',
    'unmarked': 'Unmarked',
    'class_breakdown': 'Class Breakdown',
    'no_class_data': 'No class data available.',
    'pending': 'Pending',
    'attendance_history_all_desc': 'Daily records for the entire school.',
    'search_by_date': 'Search by date...',
    'attendance_rate': 'Attendance Rate',
    'close': 'Close',
    'add_asset': 'Add Asset',
    'asset_details': 'Asset Details',
    'next_maintenance': 'Next Maintenance',
    'no_assets_found': 'No assets found.',
    'page': 'Page',
    'of': 'of',
    'add_new_asset': 'Add New Asset',
    'add_asset_desc': 'Register a new item in the school inventory.',
    'laptop': 'Laptop',
    'projector': 'Projector',
    'sports_equipment': 'Sports Equipment',
    'furniture': 'Furniture',
    'next_maintenance_date': 'Next Maintenance Date',
    'new_check_in': 'New Check-in',
    'visitor': 'Visitor',
    'purpose_host': 'Purpose & Host',
    'time': 'Time',
    'no_visitors_found': 'No visitors found.',
    'new_visitor_checkin': 'New Visitor Check-in',
    'new_visitor_desc': 'Register a new visitor and print their badge.',
    'full_name': 'Full Name',
    'purpose_of_visit': 'Purpose of Visit',
    'host_staff_member': 'Host (Staff Member)',
    'students_directory': 'Students Directory',
    'students_directory_desc': 'Manage student records and directory.',
    'add_student': 'Add Student',
    'directory': 'Directory',
    'history': 'History',
    'promotions': 'Promotions',
    'filters': 'Filters',
    'search_students': 'Search students...',
    'student': 'Student',
    'roll_number': 'Roll Number',
    'parent_guardian': 'Parent/Guardian',
    'no_students_found': 'No students found.',
    'dropped_deleted_students': 'Dropped/Deleted Students',
    'search_history': 'Search history...',
    'reason': 'Reason',
    'dropped_out': 'Dropped out',
    'transferred': 'Transferred',
    'graduated': 'Graduated',
    'restore': 'Restore',
    'student_promotions': 'Student Promotions',
    'student_promotions_desc': 'Manage student grade and class promotions.',
    'promote_by_grade': 'Promote by Grade',
    'promote_by_grade_desc': 'Promote all students in a specific grade.',
    'promote_by_class': 'Promote by Class',
    'promote_by_class_desc': 'Promote students in a specific class.',
    'manual_promotion': 'Manual Promotion',
    'manual_promotion_desc': 'Manually select students for promotion.',
    'start_promotion': 'Start Promotion',
    'promote_students': 'Promote Students',
    'promote_students_grade_desc': 'Promote all students in the selected grade.',
    'promote_students_class_desc': 'Promote all students in the selected class.',
    'promote_students_manual_desc': 'Search and select a student to promote.',
    'select_current_grade': 'Select Current Grade',
    'select_current_class': 'Select Current Class',
    'search_student': 'Search Student',
    'search_student_placeholder': 'Search by name or ID...',
    'target_grade': 'Target Grade',
    'select_target_grade': 'Select Target Grade',
    'graduated_completed': 'Graduated/Completed',
    'promotion_warning': 'This action will update the student\'s grade and enrollment status for the next academic year.',
    'delete_student': 'Delete Student',
    'delete_student_desc': 'This will soft-delete the student record.',
    'reason_for_deletion': 'Reason for Deletion',
    'delete_reason_placeholder': 'e.g., Graduated, Dropped out, Transferred...',
    'update_student_details': 'Update Student Details',
    'register_new_student': 'Register New Student',
    'modify_student_info': 'Modify existing student information.',
    'add_new_student_desc': 'Add a new student to the school database.',
    'student_id_auto': 'Student ID (Auto-generated)',
    'select_grade': 'Select Grade',
    'date_of_birth': 'Date of Birth',
    'gender': 'Gender',
    'male': 'Male',
    'female': 'Female',
    'other': 'Other',
    'blood_group': 'Blood Group',
    'residential_address': 'Residential Address',
    'enter_address_placeholder': 'Enter full address...',
    'parent_guardian_info': 'Parent/Guardian Information',
    'parent_name_search': 'Parent Name (Searchable)',
    'search_parent_placeholder': 'Search or enter name...',
    'relation_to_student': 'Relation to Student',
    'father': 'Father',
    'mother': 'Mother',
    'guardian': 'Guardian',
    'brother': 'Brother',
    'sister': 'Sister',
    'parent_phone': 'Parent Phone',
    'fee_structure': 'Fee Structure',
    'predefined': 'Predefined',
    'manual_entry': 'Manual Entry',
    'select_predefined_structure': 'Select Predefined Structure',
    'select_fee_structure': 'Select Fee Structure',
    'add_fee_item': 'Add Fee Item',
    'item_name': 'Item Name',
    'amount': 'Amount',
    'frequency': 'Frequency',
    'category': 'Category',
    'per_term': 'Per Term',
    'monthly': 'Monthly',
    'annual': 'Annual',
    'one_time': 'One-time',
    'academic': 'Academic',
    'transport': 'Transport',
    'extracurricular': 'Extracurricular',
    'facility': 'Facility',
    'additional_information': 'Additional Information',
    'additional_info_placeholder': 'Any other details (medical, allergies, etc.)...',
    'register_student': 'Register Student',
    'overview': 'Overview',
    'medical': 'Medical',
    'behavior': 'Behavior',
    'timeline': 'Timeline',
    'email_address': 'Email Address',
    'phone_number': 'Phone Number',
    'roll_no': 'Roll No.',
    'address': 'Address',
    'emergency_contact': 'Emergency Contact',
    'relation': 'Relation',
    'conditions': 'Conditions',
    'allergies': 'Allergies',
    'none_listed': 'None listed',
    'no_known_allergies': 'No known allergies',
    'no_medical_records': 'No medical records available.',
    'total_merits': 'Total Merits',
    'total_demerits': 'Total Demerits',
    'recent_records': 'Recent Records',
    'no_behavior_records': 'No behavior records found.',
    'award': 'Award',
    'alert': 'Alert',
    'file': 'File',
    'fee_management': 'Fee Management',
    'fee_management_desc': 'Track and record student payments.',
    'new_invoice': 'New Invoice',
    'collected': 'Collected',
    'pending': 'Pending',
    'overdue': 'Overdue',
    'search_invoices_placeholder': 'Search by student name or invoice ID...',
    'all': 'All',
    'structure': 'Structure',
    'standard_fee_items': 'Standard Fee Items',
    'edit': 'Edit',
    'delete': 'Delete',
    'no_invoices_found': 'No invoices found.',
    'due': 'Due',
    'record_payment': 'Record Payment',
    'edit_fee_item': 'Edit Fee Item',
    'update_fee_item_desc': 'Update the details of this standard fee.',
    'add_fee_item_desc': 'Define a new standard fee for the school.',
    'update_item': 'Update Item',
    'student_fee_profile': 'Student Fee Profile',
    'viewing_invoices_for': 'Viewing all invoices for',
    'total_outstanding': 'Total Outstanding',
    'total_paid': 'Total Paid',
    'invoice_history': 'Invoice History',
    'amount_to_pay': 'Amount to Pay',
    'payment_method': 'Payment Method',
    'cash': 'Cash',
    'bank_transfer': 'Bank Transfer',
    'cheque': 'Cheque',
    'card': 'Card',
    'reference_number': 'Reference Number',
    'void_invoice': 'Void Invoice',
    'create_new_invoice': 'Create New Invoice',
    'generate_fee_request_desc': 'Generate a new fee request for a student.',
    'select_student': 'Select Student',
    'select_student_placeholder': 'Select a student...',
    'fee_item': 'Fee Item',
    'select_fee_type': 'Select fee type...',
    'custom_fee': 'Custom Fee...',
    'communication': 'Communication',
    'communication_desc': 'Connect with the school community.',
    'notice_board': 'Notice Board',
    'direct_messages': 'Direct Messages',
    'broadcasts': 'Broadcasts',
    'new_notice': 'New Notice',
    'important_announcement': 'Important Announcement',
    'audience': 'Audience',
    'everyone': 'Everyone',
    'parents_only': 'Parents Only',
    'staff_only': 'Staff Only',
    'search_messages': 'Search messages...',
    'type_message_placeholder': 'Type your message...',
    'select_user_to_chat': 'Select a user to start chatting',
    'urgent_broadcast': 'Urgent Broadcast',
    'urgent_broadcast_desc': 'Send immediate notifications to parents and staff.',
    'delivery_method': 'Delivery Method',
    'whatsapp': 'WhatsApp',
    'app_push': 'App Push',
    'email_alert': 'Email Alert',
    'message_template': 'Message Template',
    'urgent_alert': 'Urgent Alert (Pre-approved)',
    'school_closure': 'School Closure (Pre-approved)',
    'event_reminder': 'Event Reminder',
    'custom_message': 'Custom Message (May be delayed)',
    'whatsapp_template_desc': 'WhatsApp requires pre-approved templates for immediate delivery outside the 24-hour window.',
    'notification_priority': 'Notification Priority',
    'high_priority_desc': 'High (Bypasses Do Not Disturb)',
    'normal_priority': 'Normal',
    'email_subject': 'Email Subject',
    'target_audience': 'Target Audience',
    'entire_school': 'Entire School (Parents & Staff)',
    'all_parents': 'All Parents',
    'all_staff': 'All Staff',
    'grade4_parents': 'Grade 4 Parents Only',
    'message_content': 'Message Content',
    'type_urgent_message': 'Type your urgent message here...',
    'whatsapp_concise_desc': 'Keep it concise for WhatsApp.',
    'message_length_limit': 'Message length limit.',
    'send_broadcast_now': 'Send Broadcast Now',
    'post_new_notice': 'Post New Notice',
    'broadcast_message_desc': 'Broadcast a message to the school community.',
    'mark_as_important': 'Mark as Important',
    'post_notice': 'Post Notice',
    'create_invoice': 'Create Invoice',
    'fees_payments': 'Fees & Payments',
    'manage_payments_for': 'Manage payments for',
    'total_amount_due': 'Total Amount Due',
    'outstanding_balance_warning': 'Outstanding balance requires attention',
    'pay_now': 'Pay Now',
    'assigned_fee_structure': 'Assigned Fee Structure',
    'invoice': 'Invoice',
    'paid_on': 'Paid on',
    'due_by': 'Due by',
    'downloading_receipt': 'Downloading receipt...',
    'receipt_for': 'Receipt for',
    'is_being_prepared': 'is being prepared.',
    'download_receipt': 'Download Receipt',
    'pay': 'Pay',
    'secure_checkout': 'Secure Checkout',
    'paying_for': 'Paying for',
    'paying_total_outstanding': 'Paying total outstanding balance',
    'total_to_pay': 'Total to Pay',
    'cardholder_name': 'Cardholder Name',
    'cardholder_name_placeholder': 'John Doe',
    'card_number': 'Card Number',
    'expiry_date': 'Expiry Date',
    'cvc': 'CVC',
    'pay_securely': 'Pay Securely',
    'payment_successful': 'Payment successful',
    'payment_processed_desc': 'Your payment has been processed and a receipt has been generated.',
    'failed_to_process_payment': 'Failed to process payment',
    'locale': 'en-US',
    'urgent_alert_template': 'Urgent Alert (Pre-approved)',
    'school_closure_template': 'School Closure (Pre-approved)',
    'event_reminder_template': 'Event Reminder',
    'custom_message_template': 'Custom Message (May be delayed)',
    'whatsapp_template_notice': 'WhatsApp requires pre-approved templates for immediate delivery outside the 24-hour window.',
    'email_subject_placeholder': 'e.g., URGENT: School Closure Tomorrow',
    'grade_4_parents': 'Grade 4 Parents Only',
    'urgent_message_placeholder': 'Type your urgent message here...',
    'whatsapp_concise': 'Keep it concise for WhatsApp.',
    'chars': 'chars',
    'post_new_notice_desc': 'Broadcast a message to the school community.',
    'notice_title_placeholder': 'e.g. Sports Day Rescheduled',
    'notice_content_placeholder': 'Write your announcement here...',
    'urgent': 'Urgent',
    'broadcast_sent_success': 'broadcast sent successfully to all selected recipients.',
    'failed_to_send_broadcast': 'Failed to send broadcast',
    'notice_posted_success': 'Notice posted successfully',
    'failed_to_post_notice': 'Failed to post notice',
    'failed_to_send_message': 'Failed to send message',
  },
  ar: {
    'dashboard': 'لوحة القيادة',
    'academics': 'الأكاديميين',
    'students': 'الطلاب',
    'exams': 'التقييمات',
    'schedule': 'الجدول الزمني',
    'attendance': 'الحضور',
    'visitors': 'الزوار',
    'inventory': 'المخزون',
    'fees': 'الرسوم والمدفوعات',
    'hr': 'الموارد البشرية',
    'transport': 'النقل',
    'analytics': 'التحليلات',
    'communication': 'التواصل',
    'settings': 'الإعدادات',
    'notifications': 'التنبيهات',
    'switch_language': 'تغيير اللغة',
    'toggle_theme': 'تغيير المظهر',
    'sign_out': 'تسجيل الخروج',
    'search': 'بحث...',
    'welcome': 'مرحباً بعودتك',
    'close_profile': 'إغلاق الملف الشخصي',
    'view_all_notifications': 'عرض جميع التنبيهات',
    'new': 'جديد',
    'add': 'إضافة',
    'edit': 'تعديل',
    'delete': 'حذف',
    'save': 'حفظ',
    'cancel': 'إلغاء',
    'actions': 'إجراءات',
    'status': 'الحالة',
    'name': 'الاسم',
    'date': 'التاريخ',
    'description': 'الوصف',
    'category': 'الفئة',
    'active': 'نشط',
    'inactive': 'غير نشط',
    'upcoming': 'قادم',
    'overview': 'نظرة عامة',
    'academic_years': 'السنوات الأكاديمية',
    'classes': 'الفصول',
    'subjects': 'المواد الدراسية',
    'manage': 'إدارة',
    'total': 'الإجمالي',
    'view': 'عرض',
    'loading': 'جاري التحميل...',
    'no_data': 'لا توجد بيانات',
    'success': 'تم بنجاح',
    'error': 'خطأ',
    'confirm_delete': 'هل أنت متأكد أنك تريد حذف هذا؟',
    'inventory_desc': 'إدارة أصول ومعدات المدرسة.',
    'visitors_desc': 'إدارة زوار الحرم المدرسي وتسجيل الدخول.',
    'academics_desc': 'إدارة السنوات الأكاديمية والفصول والمواد.',
    'student_id': 'رقم الطالب',
    'grade': 'الصف',
    'section': 'القسم',
    'phone': 'الهاتف',
    'email': 'البريد الإلكتروني',
    'address': 'العنوان',
    'parent_name': 'اسم ولي الأمر',
    'relation': 'العلاقة',
    'purpose': 'الغرض',
    'host': 'المضيف',
    'time_in': 'وقت الدخول',
    'time_out': 'وقت الخروج',
    'check_in': 'تسجيل دخول',
    'check_out': 'تسجيل خروج',
    'asset_name': 'اسم الأصل',
    'assigned_to': 'مخصص لـ',
    'maintenance': 'الصيانة',
    'asset': 'أصل',
    'none': 'لا يوجد',
    'account': 'الحساب',
    'profile': 'الملف الشخصي',
    'no_notifications': 'لا توجد تنبيهات جديدة',
    'across_all_grades': 'عبر جميع الصفوف',
    'active_curriculum': 'المنهج النشط',
    'no_permission': 'ليس لديك صلاحية لعرض هذه الصفحة.',
    'welcome_back': 'مرحباً بعودتك',
    'school_status_desc': 'إليك ما يحدث في مدرستك اليوم.',
    'total_students': 'إجمالي الطلاب',
    'attendance_today': 'حضور اليوم',
    'fees_collected': 'الرسوم المحصلة',
    'pending_dues': 'المستحقات المعلقة',
    'recent_activity': 'النشاط الأخير',
    'quick_actions': 'إجراءات سريعة',
    'register_student': 'تسجيل طالب',
    'manage_fees': 'إدارة الرسوم',
    'urgent_alerts': 'تنبيهات عاجلة',
    'no_urgent_alerts': 'لا توجد تنبيهات عاجلة.',
    'hello': 'مرحباً',
    'classes_today': 'لديك {count} فصول اليوم.',
    'take_attendance': 'تسجيل الحضور',
    'attendance_rate': 'نسبة الحضور',
    'upcoming_tasks': 'المهام القادمة',
    'todays_schedule': 'جدول اليوم',
    'view_full_schedule': 'عرض الجدول الكامل',
    'mark_attendance': 'رصد الحضور',
    'post_notice': 'نشر إعلان',
    'add_assessment': 'إضافة تقييم',
    'recent_notices': 'الإعلانات الأخيرة',
    'no_recent_notices': 'لا توجد إعلانات أخيرة.',
    'financial_overview': 'نظرة مالية عامة لليوم.',
    'collected_today': 'المحصل اليوم',
    'pending_fees': 'الرسوم المعلقة',
    'record_payment': 'تسجيل دفعة جديدة',
    'latest_update_child': 'إليك آخر التحديثات لطفلك.',
    'student_profile': 'ملف الطالب',
    'upcoming_assignments': 'الواجبات القادمة',
    'due': 'مستحق',
    'posted': 'نشر في',
    'by': 'بواسطة',
    'students_directory': 'دليل الطلاب',
    'students_directory_desc': 'البحث عن معلومات الاتصال والملفات الشخصية المفصلة للطلاب وأولياء الأمور.',
    'add_student': 'إضافة طالب',
    'directory': 'الدليل',
    'history': 'السجل',
    'promotions': 'الترقيات',
    'filters': 'الفلاتر',
    'search_students': 'البحث عن طلاب...',
    'student': 'طالب',
    'roll_number': 'رقم القيد',
    'parent_guardian': 'ولي الأمر/الوصي',
    'no_students_found': 'لم يتم العثور على طلاب.',
    'previous': 'السابق',
    'next': 'التالي',
    'page_of': 'صفحة {page} من {total}',
    'dropped_deleted_students': 'الطلاب المنسحبون والمحذوفون',
    'search_history': 'البحث في السجل...',
    'reason': 'السبب',
    'restore': 'استعادة',
    'student_promotions': 'ترقيات الطلاب',
    'student_promotions_desc': 'ترقية الطلاب إلى الصف أو العام الأكاديمي التالي.',
    'promote_by_grade': 'الترقية حسب الصف',
    'promote_by_grade_desc': 'ترقية جماعية لجميع الطلاب في صف معين إلى المستوى التالي.',
    'start_promotion': 'بدء الترقية',
    'promote_by_class': 'الترقية حسب الفصل',
    'promote_by_class_desc': 'ترقية الطلاب من قسم فصل معين.',
    'manual_promotion': 'ترقية يدوية',
    'manual_promotion_desc': 'اختيار طلاب فرادى للترقية يدوياً.',
    'promote_students': 'ترقية الطلاب',
    'promote_students_grade_desc': 'ترقية الطلاب حسب مستوى الصف',
    'promote_students_class_desc': 'ترقية الطلاب حسب قسم الفصل',
    'promote_students_manual_desc': 'اختيار الطلاب يدوياً للترقية',
    'select_current_grade': 'اختر الصف الحالي',
    'select_current_class': 'اختر الفصل الحالي',
    'search_student': 'البحث عن طالب',
    'search_student_placeholder': 'البحث عن اسم الطالب أو الرقم...',
    'target_grade': 'الصف المستهدف (الترقية إلى)',
    'select_target_grade': 'اختر الصف المستهدف',
    'graduated_completed': 'تخرج / اكتمل',
    'promotion_warning': 'ستؤدي ترقية الطلاب إلى تحديث صفهم الحالي وعامهم الأكاديمي. سيؤدي هذا الإجراء أيضاً إلى إنشاء سجل التحاق جديد للدورة القادمة.',
    'academic_years': 'الأعوام الأكاديمية',
    'classes_sections': 'الفصول والأقسام',
    'curriculum_subjects': 'مواد المنهج',
    'add_year': 'إضافة عام',
    'add_class': 'إضافة فصل',
    'add_subject': 'إضافة مادة',
    'edit_year': 'تعديل العام الأكاديمي',
    'edit_class': 'تعديل الفصل',
    'edit_subject': 'تعديل المادة',
    'year_name': 'اسم العام',
    'start_date': 'تاريخ البدء',
    'end_date': 'تاريخ الانتهاء',
    'grade': 'الصف',
    'section': 'القسم',
    'subject_name': 'اسم المادة',
    'subject_code': 'رمز المادة',
    'description': 'الوصف',
    'assessments': 'التقييمات',
    'gradebook': 'سجل الدرجات',
    'submissions': 'التسليمات',
    'all_assessments': 'جميع التقييمات',
    'new_assessment': 'تقييم جديد',
    'assessment_title': 'عنوان التقييم',
    'max_score': 'الدرجة القصوى',
    'due_date': 'تاريخ الاستحقاق',
    'view_submissions': 'عرض التسليمات',
    'grade_now': 'رصد الدرجات الآن',
    'select_class': 'اختر الفصل',
    'select_subject': 'اختر المادة',
    'select_assessment_to_grade': 'اختر التقييم لرصد الدرجات',
    'save_grades': 'حفظ الدرجات',
    'student_name': 'اسم الطالب',
    'score': 'الدرجة',
    'feedback': 'الملاحظات',
    'status': 'الحالة',
    'roll': 'رقم القيد',
    'back_to_list': 'العودة للقائمة',
    'instructions': 'التعليمات',
    'homework': 'واجب منزلي',
    'assignment': 'تكليف',
    'online_exam': 'امتحان أونلاين',
    'offline_exam': 'امتحان ورقي',
    'exam_date': 'تاريخ الامتحان',
    'grading': 'رصد الدرجات',
    'remember_to_save': 'تذكر الحفظ قبل المغادرة',
    'my_assignments': 'تكليفاتي',
    'past_results': 'النتائج السابقة',
    'current_gpa': 'المعدل التراكمي الحالي',
    'top_class': 'من أفضل 10% في الصف',
    'total_credits': 'إجمالي الساعات',
    'absences': 'الغيابات',
    'subject_breakdown': 'تفاصيل المواد',
    'term_1': 'الفصل الدراسي الأول',
    'todo': 'للقيام به',
    'in_progress': 'قيد التنفيذ',
    'completed': 'مكتمل',
    'academic_report': 'التقرير الأكاديمي',
    'viewing_performance_for': 'عرض الأداء لـ',
    'update_academic_year_desc': 'تحديث تفاصيل العام الأكاديمي.',
    'create_academic_year_desc': 'إنشاء فترة عام أكاديمي جديدة.',
    'update_class_desc': 'تحديث تفاصيل الفصل.',
    'create_class_desc': 'إنشاء قسم فصل جديد.',
    'update_subject_desc': 'تحديث تفاصيل المادة.',
    'create_subject_desc': 'إنشاء مادة جديدة للمنهج.',
    'attendance_history': 'سجل الحضور',
    'attendance_history_desc': 'مراجعة سجلات الحضور السابقة لفصولك.',
    'back_to_marking': 'العودة للتحضير',
    'no_history_found': 'لم يتم العثور على سجل حضور.',
    'students_marked': 'طلاب تم تحضيرهم',
    'mark_attendance': 'تحضير الطلاب',
    'no_students_attendance_desc': 'لا يوجد طلاب مسجلون في العام الأكاديمي الحالي. يرجى إضافة طلاب أولاً.',
    'register_student': 'تسجيل طالب جديد',
    'marked': 'تم تحضيرهم',
    'please_mark_all': 'يرجى تحضير جميع الطلاب',
    'saved_successfully': 'تم الحفظ بنجاح',
    'submit_attendance': 'إرسال التحضير',
    'attendance_record': 'سجل الحضور',
    'viewing_records_for': 'عرض السجلات لـ',
    'your_student': 'طالبك',
    'recent_activity': 'النشاط الأخير',
    'no_records_found': 'لم يتم العثور على سجلات حضور.',
    'present': 'حاضر',
    'absent': 'غائب',
    'late': 'متأخر',
    'excused': 'بعذر',
    'school_attendance': 'حضور المدرسة',
    'view_history': 'عرض السجل',
    'overall_attendance_for': 'إجمالي الحضور لـ',
    'students': 'طلاب',
    'late_arrivals': 'وصول متأخر',
    'absences': 'غياب',
    'unmarked': 'غير محضر',
    'class_breakdown': 'تفاصيل الفصول',
    'no_class_data': 'لا توجد بيانات للفصول.',
    'pending': 'قيد الانتظار',
    'attendance_history_all_desc': 'السجلات اليومية للمدرسة بأكملها.',
    'search_by_date': 'البحث بالتاريخ...',
    'attendance_rate': 'نسبة الحضور',
    'close': 'إغلاق',
    'add_asset': 'إضافة أصل',
    'asset_details': 'تفاصيل الأصل',
    'next_maintenance': 'الصيانة القادمة',
    'no_assets_found': 'لم يتم العثور على أصول.',
    'page': 'صفحة',
    'of': 'من',
    'add_new_asset': 'إضافة أصل جديد',
    'add_asset_desc': 'تسجيل عنصر جديد في مخزون المدرسة.',
    'laptop': 'كمبيوتر محمول',
    'projector': 'جهاز عرض',
    'sports_equipment': 'معدات رياضية',
    'furniture': 'أثاث',
    'next_maintenance_date': 'تاريخ الصيانة القادمة',
    'new_check_in': 'تسجيل دخول جديد',
    'visitor': 'زائر',
    'purpose_host': 'الغرض والمضيف',
    'time': 'الوقت',
    'no_visitors_found': 'لم يتم العثور على زوار.',
    'new_visitor_checkin': 'تسجيل دخول زائر جديد',
    'new_visitor_desc': 'تسجيل زائر جديد وطباعة بطاقته.',
    'full_name': 'الاسم الكامل',
    'purpose_of_visit': 'الغرض من الزيارة',
    'host_staff_member': 'المضيف (موظف)',
    'check_in_print': 'تسجيل الدخول وطباعة البطاقة',
    'students_directory': 'دليل الطلاب',
    'students_directory_desc': 'إدارة سجلات الطلاب والدليل.',
    'add_student': 'إضافة طالب',
    'directory': 'الدليل',
    'history': 'السجل',
    'promotions': 'الترقيات',
    'filters': 'تصفية',
    'search_students': 'البحث عن طلاب...',
    'student': 'طالب',
    'roll_number': 'رقم القيد',
    'parent_guardian': 'ولي الأمر/الوصي',
    'no_students_found': 'لم يتم العثور على طلاب.',
    'dropped_deleted_students': 'الطلاب المنسحبون/المحذوفون',
    'search_history': 'البحث في السجل...',
    'reason': 'السبب',
    'dropped_out': 'منسحب',
    'transferred': 'منقول',
    'graduated': 'متخرج',
    'restore': 'استعادة',
    'student_promotions': 'ترقيات الطلاب',
    'student_promotions_desc': 'إدارة ترقيات صفوف وفصول الطلاب.',
    'promote_by_grade': 'ترقية حسب الصف',
    'promote_by_grade_desc': 'ترقية جميع الطلاب في صف معين.',
    'promote_by_class': 'ترقية حسب الفصل',
    'promote_by_class_desc': 'ترقية الطلاب في فصل معين.',
    'manual_promotion': 'ترقية يدوية',
    'manual_promotion_desc': 'اختيار الطلاب يدوياً للترقية.',
    'start_promotion': 'بدء الترقية',
    'promote_students': 'ترقية الطلاب',
    'promote_students_grade_desc': 'ترقية جميع الطلاب في الصف المختار.',
    'promote_students_class_desc': 'ترقية جميع الطلاب في الفصل المختار.',
    'promote_students_manual_desc': 'البحث واختيار طالب لترقيته.',
    'select_current_grade': 'اختر الصف الحالي',
    'select_current_class': 'اختر الفصل الحالي',
    'search_student': 'البحث عن طالب',
    'search_student_placeholder': 'البحث بالاسم أو الرقم...',
    'target_grade': 'الصف المستهدف',
    'select_target_grade': 'اختر الصف المستهدف',
    'graduated_completed': 'متخرج/مكتمل',
    'promotion_warning': 'سيؤدي هذا الإجراء إلى تحديث صف الطالب وحالة التسجيل للعام الدراسي القادم.',
    'delete_student': 'حذف طالب',
    'delete_student_desc': 'سيؤدي هذا إلى حذف سجل الطالب مؤقتاً.',
    'reason_for_deletion': 'سبب الحذف',
    'delete_reason_placeholder': 'مثلاً: متخرج، منسحب، منقول...',
    'update_student_details': 'تحديث تفاصيل الطالب',
    'register_new_student': 'تسجيل طالب جديد',
    'modify_student_info': 'تعديل معلومات الطالب الحالية.',
    'add_new_student_desc': 'إضافة طالب جديد إلى قاعدة بيانات المدرسة.',
    'student_id_auto': 'رقم الطالب (مولد تلقائياً)',
    'select_grade': 'اختر الصف',
    'date_of_birth': 'تاريخ الميلاد',
    'gender': 'الجنس',
    'male': 'ذكر',
    'female': 'أنثى',
    'other': 'آخر',
    'blood_group': 'فصيلة الدم',
    'residential_address': 'عنوان السكن',
    'enter_address_placeholder': 'أدخل العنوان الكامل...',
    'parent_guardian_info': 'معلومات ولي الأمر/الوصي',
    'parent_name_search': 'اسم ولي الأمر (قابل للبحث)',
    'search_parent_placeholder': 'ابحث أو أدخل الاسم...',
    'relation_to_student': 'العلاقة بالطالب',
    'father': 'أب',
    'mother': 'أم',
    'guardian': 'وصي',
    'brother': 'أخ',
    'sister': 'أخت',
    'parent_phone': 'هاتف ولي الأمر',
    'fee_structure': 'هيكل الرسوم',
    'predefined': 'محدد مسبقاً',
    'manual_entry': 'إدخال يدوي',
    'select_predefined_structure': 'اختر هيكلاً محدداً مسبقاً',
    'select_fee_structure': 'اختر هيكل الرسوم',
    'add_fee_item': 'إضافة بند رسوم',
    'item_name': 'اسم البند',
    'amount': 'المبلغ',
    'frequency': 'التكرار',
    'category': 'الفئة',
    'per_term': 'لكل فصل دراسي',
    'monthly': 'شهرياً',
    'annual': 'سنوياً',
    'one_time': 'مرة واحدة',
    'academic': 'أكاديمي',
    'transport': 'نقل',
    'extracurricular': 'أنشطة إضافية',
    'facility': 'مرافق',
    'additional_information': 'معلومات إضافية',
    'additional_info_placeholder': 'أي تفاصيل أخرى (طبية، حساسية، إلخ)...',
    'register_student': 'تسجيل الطالب',
    'overview': 'نظرة عامة',
    'medical': 'طبي',
    'behavior': 'السلوك',
    'timeline': 'الجدول الزمني',
    'email_address': 'عنوان البريد الإلكتروني',
    'phone_number': 'رقم الهاتف',
    'roll_no': 'رقم القيد',
    'address': 'العنوان',
    'emergency_contact': 'جهة اتصال للطوارئ',
    'relation': 'العلاقة',
    'conditions': 'الحالات',
    'allergies': 'الحساسية',
    'none_listed': 'لا يوجد',
    'no_known_allergies': 'لا توجد حساسية معروفة',
    'no_medical_records': 'لا توجد سجلات طبية متاحة.',
    'total_merits': 'إجمالي المزايا',
    'total_demerits': 'إجمالي العيوب',
    'recent_records': 'السجلات الأخيرة',
    'no_behavior_records': 'لم يتم العثور على سجلات سلوك.',
    'award': 'جائزة',
    'alert': 'تنبيه',
    'file': 'ملف',
    'fee_management': 'إدارة الرسوم',
    'fee_management_desc': 'تتبع وتسجيل مدفوعات الطلاب.',
    'new_invoice': 'فاتورة جديدة',
    'collected': 'المحصلة',
    'pending': 'قيد الانتظار',
    'overdue': 'متأخرة',
    'search_invoices_placeholder': 'البحث باسم الطالب أو رقم الفاتورة...',
    'all': 'الكل',
    'structure': 'الهيكل',
    'standard_fee_items': 'بنود الرسوم القياسية',
    'edit': 'تعديل',
    'delete': 'حذف',
    'no_invoices_found': 'لم يتم العثور على فواتير.',
    'due': 'مستحق',
    'record_payment': 'تسجيل دفع',
    'edit_fee_item': 'تعديل بند رسوم',
    'update_fee_item_desc': 'تحديث تفاصيل هذا الرسم القياسي.',
    'add_fee_item_desc': 'تعريف رسم قياسي جديد للمدرسة.',
    'update_item': 'تحديث البند',
    'student_fee_profile': 'ملف رسوم الطالب',
    'viewing_invoices_for': 'عرض جميع الفواتير لـ',
    'total_outstanding': 'إجمالي المستحقات',
    'total_paid': 'إجمالي المدفوعات',
    'invoice_history': 'سجل الفواتير',
    'amount_to_pay': 'المبلغ المطلوب دفعه',
    'payment_method': 'طريقة الدفع',
    'cash': 'نقداً',
    'bank_transfer': 'تحويل بنكي',
    'cheque': 'شيك',
    'card': 'بطاقة',
    'reference_number': 'رقم المرجع',
    'void_invoice': 'إلغاء الفاتورة',
    'create_new_invoice': 'إنشاء فاتورة جديدة',
    'generate_fee_request_desc': 'إنشاء طلب رسوم جديد لطالب.',
    'select_student': 'اختر الطالب',
    'select_student_placeholder': 'اختر طالباً...',
    'fee_item': 'بند الرسوم',
    'select_fee_type': 'اختر نوع الرسوم...',
    'custom_fee': 'رسوم مخصصة...',
    'communication': 'التواصل',
    'communication_desc': 'تواصل مع مجتمع المدرسة.',
    'notice_board': 'لوحة الإعلانات',
    'direct_messages': 'الرسائل المباشرة',
    'broadcasts': 'البث',
    'new_notice': 'إعلان جديد',
    'important_announcement': 'إعلان هام',
    'audience': 'الجمهور',
    'everyone': 'الجميع',
    'parents_only': 'أولياء الأمور فقط',
    'staff_only': 'الموظفون فقط',
    'search_messages': 'البحث في الرسائل...',
    'type_message_placeholder': 'اكتب رسالتك...',
    'select_user_to_chat': 'اختر مستخدماً لبدء الدردشة',
    'urgent_broadcast': 'بث عاجل',
    'urgent_broadcast_desc': 'إرسال إشعارات فورية لأولياء الأمور والموظفين.',
    'delivery_method': 'طريقة التسليم',
    'whatsapp': 'واتساب',
    'app_push': 'إشعار تطبيق',
    'email_alert': 'تنبيه بريد إلكتروني',
    'message_template': 'قالب الرسالة',
    'urgent_alert': 'تنبيه عاجل (معتمد مسبقاً)',
    'school_closure': 'إغلاق المدرسة (معتمد مسبقاً)',
    'event_reminder': 'تذكير بحدث',
    'custom_message': 'رسالة مخصصة (قد تتأخر)',
    'whatsapp_template_desc': 'يتطلب واتساب قوالب معتمدة مسبقاً للتسليم الفوري خارج نافذة الـ 24 ساعة.',
    'notification_priority': 'أولوية الإشعار',
    'high_priority_desc': 'عالية (تتجاوز وضع عدم الإزعاج)',
    'normal_priority': 'عادية',
    'email_subject': 'موضوع البريد الإلكتروني',
    'target_audience': 'الجمهور المستهدف',
    'entire_school': 'المدرسة بأكملها (أولياء أمور وموظفون)',
    'all_parents': 'جميع أولياء الأمور',
    'all_staff': 'جميع الموظفين',
    'grade4_parents': 'أولياء أمور الصف الرابع فقط',
    'message_content': 'محتوى الرسالة',
    'type_urgent_message': 'اكتب رسالتك العاجلة هنا...',
    'whatsapp_concise_desc': 'اجعلها موجزة للواتساب.',
    'message_length_limit': 'حد طول الرسالة.',
    'send_broadcast_now': 'إرسال البث الآن',
    'post_new_notice': 'نشر إعلان جديد',
    'broadcast_message_desc': 'بث رسالة لمجتمع المدرسة.',
    'mark_as_important': 'تحديد كـ هام',
    'post_notice': 'نشر الإعلان',
    'create_invoice': 'إنشاء فاتورة',
    'fees_payments': 'الرسوم والمدفوعات',
    'manage_payments_for': 'إدارة المدفوعات لـ',
    'total_amount_due': 'إجمالي المبلغ المستحق',
    'outstanding_balance_warning': 'الرصيد المستحق يتطلب الاهتمام',
    'pay_now': 'ادفع الآن',
    'assigned_fee_structure': 'هيكل الرسوم المخصص',
    'invoice': 'فاتورة',
    'paid_on': 'تم الدفع في',
    'due_by': 'يستحق في',
    'downloading_receipt': 'جاري تحميل الإيصال...',
    'receipt_for': 'إيصال لـ',
    'is_being_prepared': 'جاري تجهيزه.',
    'download_receipt': 'تحميل الإيصال',
    'pay': 'دفع',
    'secure_checkout': 'الدفع الآمن',
    'paying_for': 'دفع لـ',
    'paying_total_outstanding': 'دفع إجمالي الرصيد المستحق',
    'total_to_pay': 'الإجمالي للدفع',
    'cardholder_name': 'اسم حامل البطاقة',
    'cardholder_name_placeholder': 'مثلاً: محمد أحمد',
    'card_number': 'رقم البطاقة',
    'expiry_date': 'تاريخ الانتهاء',
    'cvc': 'رمز التحقق (CVC)',
    'pay_securely': 'ادفع بأمان',
    'payment_successful': 'تم الدفع بنجاح',
    'payment_processed_desc': 'تمت معالجة دفعتك وإنشاء إيصال.',
    'failed_to_process_payment': 'فشل في معالجة الدفعة',
    'locale': 'ar-SA',
    'urgent_alert_template': 'تنبيه عاجل (معتمد مسبقاً)',
    'school_closure_template': 'إغلاق المدرسة (معتمد مسبقاً)',
    'event_reminder_template': 'تذكير بحدث',
    'custom_message_template': 'رسالة مخصصة (قد تتأخر)',
    'whatsapp_template_notice': 'يتطلب واتساب قوالب معتمدة مسبقاً للتسليم الفوري خارج نافذة الـ 24 ساعة.',
    'email_subject_placeholder': 'مثلاً: عاجل: إغلاق المدرسة غداً',
    'grade_4_parents': 'أولياء أمور الصف الرابع فقط',
    'urgent_message_placeholder': 'اكتب رسالتك العاجلة هنا...',
    'whatsapp_concise': 'اجعلها موجزة للواتساب.',
    'chars': 'حرف',
    'post_new_notice_desc': 'نشر رسالة لمجتمع المدرسة.',
    'notice_title_placeholder': 'مثلاً: تغيير موعد اليوم الرياضي',
    'notice_content_placeholder': 'اكتب إعلانك هنا...',
    'urgent': 'عاجل',
    'broadcast_sent_success': 'تم إرسال البث بنجاح لجميع المستلمين المختارين.',
    'failed_to_send_broadcast': 'فشل في إرسال البث',
    'notice_posted_success': 'تم نشر الإعلان بنجاح',
    'failed_to_post_notice': 'فشل في نشر الإعلان',
    'failed_to_send_message': 'فشل في إرسال الرسالة',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      const savedLang = localStorage.getItem('language') as Language;
      if (savedLang && (savedLang === 'en' || savedLang === 'ar')) {
        return savedLang;
      }
    }
    return 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  useEffect(() => {
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string) => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  const isRTL = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
