'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations = {
  en: {
    'dashboard': 'Dashboard',
    'academics': 'Academics',
    'students': 'Students',
    'parent': 'Parent',
    'report_cards': 'Report Cards',
    'exams': 'Assessments',
    'schedule': 'Schedule',
    'attendance': 'Attendance',
    'visitors': 'Visitors',
    'inventory': 'Inventory',
    'fees': 'Fees & Payments',
    'hr': 'HR',
    'transport': 'Transport',
    'analytics': 'Analytics',
    'communication': 'Notices',
    'settings': 'Settings',
    'notifications': 'Notifications',
    'switch_language': 'Switch Language',
    'toggle_theme': 'Toggle Theme',
    'sign_out': 'Sign Out',
    'search': 'Search...',
    'welcome': 'Welcome back',
    'close_profile': 'Close Profile',
    'view_all_notifications': 'View All Notifications',
    'new': 'New',
    'add': 'Add',
    'edit': 'Edit',
    'delete': 'Delete',
    'save': 'Save',
    'cancel': 'Cancel',
    'actions': 'Actions',
    'status': 'Status',
    'name': 'Name',
    'date': 'Date',
    'description': 'Description',
    'category': 'Category',
    'active': 'Active',
    'inactive': 'Inactive',
    'upcoming': 'Upcoming',
    'overview': 'Overview',
    'assessments': 'Assessments',
    'payments': 'Payments',
    'no_assessments': 'No assessments found for this student',
    'no_payments': 'No payment records found for this student',
    'due_date': 'Due Date',
    'amount': 'Amount',
    'academic_years': 'Academic Years',
    'classes': 'Classes',
    'subjects': 'Subjects',
    'manage': 'Manage',
    'total': 'Total',
    'view': 'View',
    'loading': 'Loading...',
    'no_data': 'No data found',
    'success': 'Success',
    'error': 'Error',
    'confirm_delete': 'Are you sure you want to delete this?',
    'delete_confirmation': 'Are you sure?',
    'delete_fee_item_warning': 'This action will permanently remove this fee item from the standard structure. Existing invoices will not be affected.',
    'inventory_desc': 'Manage school assets and equipment.',
    'visitors_desc': 'Manage campus visitors and check-ins.',
    'academics_desc': 'Manage academic years, classes, and subjects.',
    'student_id': 'Student ID',
    'grade': 'Grade',
    'section': 'Section',
    'phone': 'Phone',
    'email': 'Email',
    'address': 'Address',
    'parent_name': 'Parent Name',
    'relation': 'Relation',
    'purpose': 'Purpose',
    'host': 'Host',
    'time_in': 'Time In',
    'time_out': 'Time Out',
    'check_in': 'Check In',
    'check_out': 'Check Out',
    'asset_name': 'Asset Name',
    'assigned_to': 'Assigned To',
    'asset': 'Asset',
    'none': 'None',
    'account': 'Account',
    'no_notifications': 'No new notifications',
    'across_all_grades': 'Across all grades',
    'password': 'Password',
    'forgot_password': 'Forgot?',
    'sign_in_to_dashboard': 'Sign In to Dashboard',
    'mvp_quick_login': 'MVP Quick Login',
    'built_with_love': 'Built with ❤️ by AwoodaTech™',
    'active_curriculum': 'Active curriculum',
    'no_permission': 'You do not have permission to view this page.',
    'welcome_back': 'Welcome back',
    'school_status_desc': 'Here is what\'s happening with your school today.',
    'total_students': 'Total Students',
    'attendance_today': 'Attendance Today',
    'fees_collected': 'Fees Collected',
    'pending_dues': 'Pending Dues',
    'recent_activity': 'Recent Activity',
    'quick_actions': 'Quick Actions',
    'register_student': 'Register Student',
    'manage_fees': 'Manage Fees',
    'urgent_alerts': 'Urgent Alerts',
    'no_urgent_alerts': 'No urgent alerts.',
    'hello': 'Hello',
    'classes_today': 'You have {count} classes today.',
    'take_attendance': 'Take Attendance',
    'attendance_rate': 'Attendance Rate',
    'upcoming_tasks': 'Upcoming Tasks',
    'todays_schedule': 'Today\'s Schedule',
    'view_full_schedule': 'View Full Schedule',
    'mark_attendance': 'Mark Attendance',
    'post_notice': 'Post Notice',
    'add_assessment': 'Add Assessment',
    'recent_notices': 'Recent Notices',
    'no_recent_notices': 'No recent notices.',
    'financial_overview': 'Financial overview for today.',
    'collected_today': 'Collected Today',
    'pending_fees': 'Pending Fees',
    'record_payment': 'Record New Payment',
    'latest_update_child': 'Here is the latest update for your child.',
    'student_profile': 'Student Profile',
    'upcoming_assignments': 'Upcoming Assignments',
    'due': 'Due',
    'posted': 'Posted',
    'by': 'by',
    'students_directory': 'Students Directory',
    'students_directory_desc': 'Find contact information and detailed profiles for students and parents.',
    'add_student': 'Add Student',
    'grade_cards': 'Grade Cards',
    'filters': 'Filters',
    'search_students': 'Search students...',
    'student': 'Student',
    'roll_number': 'Roll Number',
    'no_students_found': 'No students found.',
    'previous': 'Previous',
    'next': 'Next',
    'page_of': 'Page {page} of {total}',
    'dropped_deleted_students': 'Dropped & Deleted Students',
    'search_history': 'Search history...',
    'reason': 'Reason',
    'restore': 'Restore',
    'classes_grades': 'Classes / Grades',
    'classes_grades_desc': 'Select a class to enter grades for its students.',
    'select_grade': 'Select Grade',
    'open_register': 'Open Register',
    'promote_by_grade': 'Promote by Grade',
    'promote_by_grade_desc': 'Bulk promote all students in a specific grade to the next level.',
    'start_promotion': 'Start Promotion',
    'promote_by_class': 'Promote by Class',
    'promote_by_class_desc': 'Promote students from a specific class section.',
    'manual_promotion': 'Manual Promotion',
    'manual_promotion_desc': 'Select individual students to promote manually.',
    'promote_students': 'Promote Students',
    'promote_students_grade_desc': 'Promote students by grade level',
    'promote_students_class_desc': 'Promote students by class section',
    'promote_students_manual_desc': 'Manually select students to promote',
    'select_current_grade': 'Select Current Grade',
    'select_current_class': 'Select Current Class',
    'search_student': 'Search Student',
    'search_student_placeholder': 'Search student name or ID...',
    'target_grade': 'Target Grade (Promotion To)',
    'select_target_grade': 'Select Target Grade',
    'graduated_completed': 'Graduated / Completed',
    'promotion_warning': 'Promoting students will update their current grade and academic year. This action will also create a new enrollment record for the upcoming session.',
    'classes_sections': 'Classes & Sections',
    'curriculum_subjects': 'Curriculum Subjects',
    'add_year': 'Add Year',
    'add_class': 'Add Class',
    'add_subject': 'Add Subject',
    'edit_year': 'Edit Academic Year',
    'edit_class': 'Edit Class',
    'edit_subject': 'Edit Subject',
    'year_name': 'Year Name',
    'start_date': 'Start Date',
    'end_date': 'End Date',
    'subject_name': 'Subject Name',
    'subject_code': 'Subject Code',
    'gradebook': 'Gradebook',
    'submissions': 'Submissions',
    'all_assessments': 'All Assessments',
    'new_assessment': 'New Assessment',
    'assessment_title': 'Assessment Title',
    'max_score': 'Max Score',
    'view_submissions': 'View Submissions',
    'grade_now': 'Grade Now',
    'select_class': 'Select Class',
    'select_subject': 'Select Subject',
    'select_assessment_to_grade': 'Select Assessment to Grade',
    'save_grades': 'Save Grades',
    'student_name': 'Student Name',
    'feedback': 'Feedback',
    'roll': 'Roll',
    'back_to_list': 'Back to List',
    'instructions': 'Instructions',
    'homework': 'Homework',
    'assignment': 'Assignment',
    'online_exam': 'Online Exam',
    'offline_exam': 'Offline Exam',
    'exam_date': 'Exam Date',
    'grading': 'Grading',
    'remember_to_save': 'Remember to save before leaving',
    'my_assignments': 'My Assignments',
    'past_results': 'Past Results',
    'current_gpa': 'Current GPA',
    'top_class': 'Top 10% of Class',
    'total_credits': 'Total Credits',
    'absences': 'Absences',
    'subject_breakdown': 'Subject Breakdown',
    'term_1': 'Term 1',
    'todo': 'To Do',
    'in_progress': 'In Progress',
    'completed': 'Completed',
    'academic_report': 'Academic Report',
    'viewing_performance_for': 'Viewing performance for',
    'update_academic_year_desc': 'Update academic year details.',
    'create_academic_year_desc': 'Create a new academic year period.',
    'update_class_desc': 'Update class details.',
    'create_class_desc': 'Create a new class section.',
    'update_subject_desc': 'Update subject details.',
    'create_subject_desc': 'Create a new subject for the curriculum.',
    'attendance_history': 'Attendance History',
    'attendance_history_desc': 'Review past attendance records for your classes.',
    'back_to_marking': 'Back to Marking',
    'no_history_found': 'No attendance history found.',
    'students_marked': 'Students Marked',
    'no_students_attendance_desc': 'There are no students registered for the current academic year. Please add students first.',
    'marked': 'Marked',
    'please_mark_all': 'Please mark all students',
    'saved_successfully': 'Saved Successfully',
    'submit_attendance': 'Submit Attendance',
    'overview_dashboard': 'Overview Dashboard',
    'mark_all_present': 'Mark All Present',
    'all_classes': 'All Classes',
    'attendance_details': 'Attendance Details',
    'loading_details': 'Loading details...',
    'no_grade': 'No Grade',
    'marked_all_present_toast': 'Marked all unmarked students as Present',
    'attendance_record': 'Attendance Record',
    'viewing_records_for': 'Viewing records for',
    'your_student': 'your student',
    'present': 'Present',
    'absent': 'Absent',
    'late': 'Late',
    'excused': 'Excused',
    'view_history': 'View History',
    'overall_attendance_for': 'Overall Attendance for',
    'late_arrivals': 'Late Arrivals',
    'unmarked': 'Unmarked',
    'class_breakdown': 'Class Breakdown',
    'no_class_data': 'No class data available.',
    'pending': 'Pending',
    'attendance_history_all_desc': 'Daily records for the entire school.',
    'search_by_date': 'Search by date...',
    'close': 'Close',
    'add_asset': 'Add Asset',
    'asset_details': 'Asset Details',
    'next_maintenance': 'Next Maintenance',
    'no_assets_found': 'No assets found.',
    'page': 'Page',
    'of': 'of',
    'add_new_asset': 'Add New Asset',
    'add_asset_desc': 'Register a new item in the school inventory.',
    'laptop': 'Laptop',
    'projector': 'Projector',
    'sports_equipment': 'Sports Equipment',
    'furniture': 'Furniture',
    'next_maintenance_date': 'Next Maintenance Date',
    'new_check_in': 'New Check-in',
    'visitor': 'Visitor',
    'purpose_host': 'Purpose & Host',
    'time': 'Time',
    'no_visitors_found': 'No visitors found.',
    'new_visitor_checkin': 'New Visitor Check-in',
    'new_visitor_desc': 'Register a new visitor and print their badge.',
    'full_name': 'Full Name',
    'purpose_of_visit': 'Purpose of Visit',
    'host_staff_member': 'Host (Staff Member)',
    'dropped_out': 'Dropped out',
    'transferred': 'Transferred',
    'delete_student': 'Delete Student',
    'delete_student_desc': 'This will soft-delete the student record.',
    'reason_for_deletion': 'Reason for Deletion',
    'delete_reason_placeholder': 'e.g., Graduated, Dropped out, Transferred...',
    'update_student_details': 'Update Student Details',
    'register_new_student': 'Register New Student',
    'modify_student_info': 'Modify existing student information.',
    'add_new_student_desc': 'Add a new student to the school database.',
    'student_id_auto': 'Student ID (Auto-generated)',
    'other': 'Other',
    'residential_address': 'Residential Address',
    'enter_address_placeholder': 'Enter full address...',
    'parent_guardian_info': 'Parent/Guardian Information',
    'parent_name_search': 'Parent Name (Searchable)',
    'search_parent_placeholder': 'Search or enter name...',
    'relation_to_student': 'Relation to Student',
    'father': 'Father',
    'mother': 'Mother',
    'guardian': 'Guardian',
    'brother': 'Brother',
    'sister': 'Sister',
    'parent_phone': 'Parent Phone',
    'predefined': 'Predefined',
    'manual_entry': 'Manual Entry',
    'select_predefined_structure': 'Select Predefined Structure',
    'select_fee_structure': 'Select Fee Structure',
    'add_fee_item': 'Add Fee Item',
    'item_name': 'Item Name',
    'frequency': 'Frequency',
    'per_term': 'Per Term',
    'monthly': 'Monthly',
    'annual': 'Annual',
    'one_time': 'One-time',
    'academic': 'Academic',
    'extracurricular': 'Extracurricular',
    'facility': 'Facility',
    'additional_information': 'Additional Information',
    'additional_info_placeholder': 'Any other details (medical, allergies, etc.)...',
    'medical': 'Medical',
    'behavior': 'Behavior',
    'timeline': 'Timeline',
    'emergency_contact': 'Emergency Contact',
    'conditions': 'Conditions',
    'allergies': 'Allergies',
    'none_listed': 'None listed',
    'no_known_allergies': 'No known allergies',
    'no_medical_records': 'No medical records available.',
    'total_merits': 'Total Merits',
    'total_demerits': 'Total Demerits',
    'recent_records': 'Recent Records',
    'no_behavior_records': 'No behavior records found.',
    'award': 'Award',
    'file': 'File',
    'fee_management': 'Fee Management',
    'fee_management_desc': 'Track and record student payments.',
    'new_invoice': 'New Invoice',
    'collected': 'Collected',
    'overdue': 'Overdue',
    'search_invoices_placeholder': 'Search by student name or invoice ID...',
    'all': 'All',
    'structure': 'Structure',
    'standard_fee_items': 'Standard Fee Items',
    'no_invoices_found': 'No invoices found.',
    'edit_fee_item': 'Edit Fee Item',
    'update_fee_item_desc': 'Update the details of this standard fee.',
    'add_fee_item_desc': 'Define a new standard fee for the school.',
    'update_item': 'Update Item',
    'total_paid': 'Total Paid',
    'invoice_history': 'Invoice History',
    'payment_method': 'Payment Method',
    'cash': 'Cash',
    'bank_transfer': 'Bank Transfer',
    'cheque': 'Cheque',
    'card': 'Card',
    'reference_number': 'Reference Number',
    'void_invoice': 'Void Invoice',
    'create_new_invoice': 'Create New Invoice',
    'generate_fee_request_desc': 'Generate a new fee request for a student.',
    'select_student': 'Select Student',
    'select_student_placeholder': 'Select a student...',
    'fee_item': 'Fee Item',
    'select_fee_type': 'Select fee type...',
    'custom_fee': 'Custom Fee...',
    'communication_desc': 'School-wide announcements and notices.',
    'notice_board': 'Notice Board',
    'direct_messages': 'Direct Messages',
    'broadcasts': 'Broadcasts',
    'new_notice': 'New Notice',
    'important_announcement': 'Important Announcement',
    'everyone': 'Everyone',
    'parents_only': 'Parents Only',
    'staff_only': 'Staff Only',
    'search_messages': 'Search messages...',
    'type_message_placeholder': 'Type your message...',
    'select_user_to_chat': 'Select a user to start chatting',
    'urgent_broadcast': 'Urgent Broadcast',
    'urgent_broadcast_desc': 'Send immediate notifications to parents and staff.',
    'delivery_method': 'Delivery Method',
    'whatsapp': 'WhatsApp',
    'app_push': 'App Push',
    'message_template': 'Message Template',
    'urgent_alert': 'Urgent Alert (Pre-approved)',
    'school_closure': 'School Closure (Pre-approved)',
    'event_reminder': 'Event Reminder',
    'custom_message': 'Custom Message (May be delayed)',
    'whatsapp_template_desc': 'WhatsApp requires pre-approved templates for immediate delivery outside the 24-hour window.',
    'notification_priority': 'Notification Priority',
    'high_priority_desc': 'High (Bypasses Do Not Disturb)',
    'normal_priority': 'Normal',
    'email_subject': 'Email Subject',
    'target_audience': 'Target Audience',
    'entire_school': 'Entire School (Parents & Staff)',
    'all_parents': 'All Parents',
    'all_staff': 'All Staff',
    'grade4_parents': 'Grade 4 Parents Only',
    'message_content': 'Message Content',
    'type_urgent_message': 'Type your urgent message here...',
    'whatsapp_concise_desc': 'Keep it concise for WhatsApp.',
    'message_length_limit': 'Message length limit.',
    'send_broadcast_now': 'Send Broadcast Now',
    'post_new_notice': 'Post New Notice',
    'broadcast_message_desc': 'Broadcast a message to the school community.',
    'mark_as_important': 'Mark as Important',
    'create_invoice': 'Create Invoice',
    'fees_payments': 'Fees & Payments',
    'manage_payments_for': 'Manage payments for',
    'total_amount_due': 'Total Amount Due',
    'pay_now': 'Pay Now',
    'assigned_fee_structure': 'Assigned Fee Structure',
    'invoice': 'Invoice',
    'pay': 'Pay',
    'payment_successful': 'Payment successful',
    'payment_processed_desc': 'Your payment has been processed and a receipt has been generated.',
    'failed_to_process_payment': 'Failed to process payment',
    'locale': 'en-US',
    'urgent_alert_template': 'Urgent Alert (Pre-approved)',
    'school_closure_template': 'School Closure (Pre-approved)',
    'event_reminder_template': 'Event Reminder',
    'custom_message_template': 'Custom Message (May be delayed)',
    'whatsapp_template_notice': 'WhatsApp requires pre-approved templates for immediate delivery outside the 24-hour window.',
    'email_subject_placeholder': 'e.g., URGENT: School Closure Tomorrow',
    'grade_4_parents': 'Grade 4 Parents Only',
    'urgent_message_placeholder': 'Type your urgent message here...',
    'whatsapp_concise': 'Keep it concise for WhatsApp.',
    'chars': 'chars',
    'post_new_notice_desc': 'Broadcast a message to the school community.',
    'notice_title_placeholder': 'e.g. Sports Day Rescheduled',
    'notice_content_placeholder': 'Write your announcement here...',
    'urgent': 'Urgent',
    'broadcast_sent_success': 'broadcast sent successfully to all selected recipients.',
    'failed_to_send_broadcast': 'Failed to send broadcast',
    'notice_posted_success': 'Notice posted successfully',
    'failed_to_post_notice': 'Failed to post notice',
    'failed_to_send_message': 'Failed to send message',
    'submissions_for': 'Submissions: {title}',
    'go_to_gradebook': 'Go to Gradebook',
    'submitted_today': 'Submitted today',
    'submitted_yesterday': 'Submitted yesterday',
    'review_submission': 'Review Submission',
    'graded_on': 'Graded on {date}',
    'assessment_label': 'Assessment',
    'student_work': 'Student Work',
    'no_content_provided': 'No content provided.',
    'grade_score_max': 'Grade / Score (Max: {max})',
    'enter_score': 'Enter score...',
    'needs_revision': 'Needs Revision',
    'feedback_for_student': 'Feedback for Student',
    'provide_feedback_placeholder': 'Provide constructive feedback...',
    'submit_grade': 'Submit Grade',
    'could_not_identify_student': 'Could not identify student',
    'assignment_submitted_success': 'Assignment submitted successfully!',
    'failed_to_submit_assignment': 'Failed to submit assignment',
    'complete_percentage': '{percentage}% Complete',
    'pending_grading': 'Pending Grading',
    'no_instructions_provided': 'No additional instructions provided.',
    'your_work': 'Your Work',
    'uploading': 'Uploading...',
    'click_to_upload': 'Click to upload or drag and drop',
    'upload_limits': 'PDF, DOCX, PPTX, or Images (max. 10MB)',
    'private_comment_placeholder': 'Add a private comment to your teacher...',
    'mark_as_done': 'Mark as Done',
    'teacher_feedback': 'Teacher Feedback',
    'score_label': 'Score',
    'class_name': 'Class Name',
    'academic_year': 'Academic Year',
    'attendance_saved_desc': 'Recorded attendance for {count} students.',
    'failed_to_save_attendance': 'Failed to save attendance',
    'attendance_saved_success': 'Attendance saved successfully',
    'online_exams': 'Online Exams',
    'exams_student_desc': 'View and take your assessments',
    'exams_admin_desc': 'Manage online exams and assessments',
    'create_exam': 'Create Exam',
    'search_exams_placeholder': 'Search exams by title or subject...',
    'all_status': 'All Status',
    'live_now': 'Live Now',
    'no_exams_found': 'No exams found.',
    'minutes': 'Minutes',
    'questions': 'Questions',
    'marks': 'Marks',
    'start_exam': 'Start Exam',
    'monitor_live': 'Monitor Live',
    'starts_soon': 'Starts Soon',
    'view_results': 'View Results',
    'view_analytics': 'View Analytics',
    'page_label': 'Page',
    'of_label': 'of',
    'total_label': 'Total',
    'create_new_exam': 'Create New Exam',
    'exam_create_desc': 'Configure exam details and add questions',
    'save_exam': 'Save Exam',
    'saving': 'Saving...',
    'exam_settings_step': '1. Exam Settings',
    'questions_step': '2. Questions',
    'exam_title_label': 'Exam Title',
    'exam_title_placeholder': 'e.g. Mid-Term Mathematics',
    'target_grade_label': 'Target Grade',
    'assessment_type_label': 'Assessment Type',
    'duration_minutes_label': 'Duration (Minutes)',
    'auto_calculated': '(Auto-calculated)',
    'description_label': 'Description',
    'exam_desc_placeholder': 'Enter assessment instructions or description...',
    'continue_to_questions': 'Continue to Questions',
    'add_question': 'Add Question',
    'question_details': 'Question Details',
    'question_text_label': 'Question Text',
    'question_text_placeholder': 'Enter your question here...',
    'question_type_label': 'Question Type',
    'multiple_choice': 'Multiple Choice',
    'true_false': 'True / False',
    'multiple_response': 'Multiple Response (Checkboxes)',
    'short_answer': 'Short Answer (Exact Match)',
    'marks_label': 'Marks',
    'options_correct_answer': 'Options & Correct Answer',
    'option_label': 'Option',
    'correct_answer_label': 'Correct Answer',
    'true_label': 'True',
    'false_label': 'False',
    'short_answer_placeholder': 'Enter the exact correct answer...',
    'short_answer_note': 'Note: Student response must match this exactly (case-insensitive check can be implemented in the grading logic).',
    'add_another_question': 'Add Another Question',
    'active_year_not_found': 'Active academic year not found',
    'assessment_created_success': 'Assessment created successfully',
    'failed_to_create_assessment': 'Failed to create assessment',
    'exam_submitted_success': 'Exam Submitted Successfully!',
    'exam_submitted_desc': 'Your answers have been recorded. You can view your results once the teacher publishes them.',
    'answered': 'Answered',
    'submit_exam': 'Submit Exam',
    'submitting': 'Submitting...',
    'question_label': 'Question',
    'flag_for_review': 'Flag for review',
    'type_answer_placeholder': 'Type your answer here...',
    'question_navigator': 'Question Navigator',
    'unanswered': 'Unanswered',
    'submit_exam_confirm': 'Are you sure you want to submit your exam? You cannot change your answers after submitting.',
    'todays_attendance': "Today's Attendance",
    'collection_gap': 'Collection Gap',
    'revenue': 'Revenue',
    'pending_receivables': 'Pending Receivables',
    'active_members': 'active members',
    'publications': 'publications',
    'financial_pulse': 'Financial Pulse',
    'revenue_analysis': 'Revenue vs Receivables Analysis',
    'directives': 'Directives',
    'no_active_directives': 'No Active Directives',
    'academic_trajectory': 'Academic Trajectory',
    'growth_in_progress': 'Growth in Progress',
    'milestones_achieved': 'All current milestones successfully achieved.',
    'live_presence': 'Live Presence',
    'status_active': 'Status Active',
    'next_milestone': 'Next Milestone',
    'take_task': 'Take Task',
    'activity_logs': 'Activity Logs',
    'recent_audits': 'Recent Audits & Intelligence',
    'today_revenue': "Today's Revenue",
    'staff_faculty': 'Staff & Faculty',
    'live_notices': 'Live Notices',
    'student_enrolled': 'New Student Enrolled',
    'staff_created': 'New Staff Member Onboarded',
    'fee_invoice_generated': 'Fee Invoice Generated',
    'fee_invoice_voided': 'Fee Invoice Voided',
    'payment_recorded': 'Payment Recorded',
    'assessment_created': 'New Assessment Created',
    'bulk_attendance_saved': 'Bulk Attendance Saved',
    'active_classes_count': 'active classes',
    'students_present_count': 'students present',
    'today': 'today',
    'ago': 'ago',
    'm': 'm',
    'h': 'h',
    'd': 'd',
    'engagement': 'Engagement',
    'tasks': 'Tasks',
    'classroom_intelligence': 'Classroom Intelligence',
    'todays_agenda': "Today's Agenda",
    'full_schedule': 'Full Schedule',
    'intelligence_feed': 'Intelligence Feed',
    'broadcast': 'Broadcast',
    'no_classes_scheduled': 'No Classes Scheduled',
    'enjoy_prep_time': 'Enjoy your preparation time!',
    'total_ytd': 'Total YTD',
    'outstanding': 'Outstanding',
    'no_financial_directives': 'No Financial Directives',
    'run_invoice_audit': 'Run Invoice Audit',
    'configure_fee_tiers': 'Configure Fee Tiers',
    'security_note': 'Security Note',
    'payment_integrity_msg': 'All payment records are cryptographically signed and audited for multi-tenant integrity.',
    'free_day': 'Free Day',
    'no_scheduled_classes': 'No scheduled classes for today.',
    'financial_command': 'Financial Command',
    'attendance_pulse': 'Attendance Pulse',
    'daily_flow_stats': 'Daily Flow Statistics',
    'on_campus': 'On Campus',
    'operations_log': 'Operations Log',
    'live_feed': 'Live Feed',
    'quick_hub': 'Quick Hub',
    'billing': 'Billing',
    'alert': 'Alert',
    'high_priority': 'High Priority',
    'no_critical_alerts': 'No Critical Priority Alerts',
    'full_systems_audit': 'Full Systems Audit',
    'collected_label': 'Collected',
    'notifications_blocked': 'Notifications Blocked',
    'notifications_blocked_desc': 'Please unblock notifications from your browser site settings to receive live alerts.',
    'online_sync': 'Online Sync',
    'offline_local': 'Offline (Local First)',
    'publisher': 'Publisher',
    'audience': 'Audience',
    'open_notice_board': 'Open Notice Board',
    'system_online_msg': 'System Online: Real-time Live Sync active',
    'offline_mode_msg': 'Offline Mode: Data stored locally and queuing for sync',
    'profile': 'Profile',
    'audit_logs': 'Audit Logs',
    'loading_dashboard': 'Loading dashboard...',
    'statement_of_account': 'Statement of Account',
    'email_address': 'Email Address',
    'phone_number': 'Phone Number',
    'roll_no': 'Roll Number',
    'gender': 'Gender',
    'parent_guardian': 'Parent/Guardian',
    'file_attachment_library': 'File Attachment Library',
    'upload_document': 'Upload Document',
    'registry_empty': 'Registry currently empty',
    'registry_empty_desc': 'Securely archive birth certificates, IDs, and marks here.',
    'transaction_details': 'Transaction Details',
    'original_amount': 'Original Amount',
    'paid_so_far': 'Paid So Far',
    'remaining_balance': 'Remaining Balance',
    'transaction_ledger': 'Transaction Ledger',
    'amount_details': 'Amount Details',
    'balance_due': 'Balance Due',
    'paid_on': 'Paid On',
    'due_by': 'Due By',
    'unknown_assessment': 'Unknown Assessment',
    'graded': 'Graded',
    'submitted': 'Submitted',
    'score': 'Score',
    'date_of_birth': 'Date of Birth',
    'profile_security': 'Profile & Security',
    'general_preferences': 'General & Preferences',
    'roles_permissions': 'Roles & Permissions',
    'data_management': 'Data Management',
    'advanced_configurations': 'Advanced Configurations',
    'save_changes': 'Save Changes',
    'confirm': 'Confirm',
    'action_confirmation': 'Action Confirmation',
    'please_wait_moment': 'Please wait a moment...',
    'profile_settings_title': 'Profile & Settings',
    'profile_settings_desc': 'Manage your account settings and preferences.',
    'discard_changes_msg': 'Changes discarded',
    'profile_updated_success': 'Profile updated successfully',
    'users_passwords': 'Users & Passwords',
    'outstanding_balance_warning': 'Action required: You have an outstanding balance that needs your attention.',
    'assigned_plan': 'Assigned Plan',
    'discount_scholarship': 'Discount / Scholarship',
    'total_invoiced': 'Total Invoiced',
    'paid_in_full': 'Paid in full',
    'financial_standing_ledger': 'Financial Standing & Ledger Overview',
    'secure_checkout': 'Secure Checkout',
    'paying_for': 'Paying for',
    'paying_total_outstanding': 'Paying total outstanding balance',
    'total_to_pay': 'Total Amount to Pay',
    'payment_amount_label': 'Payment Amount ($)',
    'max_remaining': 'Max Remaining',
    'cardholder_name': 'Cardholder Name',
    'cardholder_name_placeholder': 'e.g. John Doe',
    'card_number': 'Card Number',
    'expiry_date': 'Expiry Date',
    'cvc': 'CVC',
    'pay_securely': 'Pay Securely',
    'invoice_details': 'Invoice Details',
    'viewing_complete_financial': 'Viewing complete financial details for this invoice.',
    'term_description': 'Term / Description',
    'payment_transaction_history': 'Payment Transaction History',
    'no_payment_transactions': 'No payment transactions recorded for this invoice yet.',
    'download_receipt': 'Download Receipt',
    'downloading_receipt': 'Downloading Receipt',
    'receipt_for': 'Receipt for',
    'is_being_prepared': 'is being prepared',
    'net_cash_flow': 'Net Cash Flow',
    'revenue_efficiency': 'Revenue Efficiency',
    'total_receivables': 'Total Receivables',
    'operational_spend': 'Operational Spend',
    'this_month': 'this month',
    'is_strictly_overdue': 'is strictly overdue',
    'monthly_burn': 'Monthly burn',
    'all_dues': 'All Dues',
    'due_this_month': 'Due This Month',
    'due_next_month': 'Due Next Month',
    'void_refund': 'Void / Refund',
    'paid_invoices': 'Paid Invoices',
    'student_fee_profile': 'Student Fee Profile',
    'viewing_invoices_for': 'Viewing detailed invoice history for',
    'total_outstanding': 'Total Outstanding',
    'recording_payment_for': 'Recording incoming payment for',
    'amount_to_pay': 'Amount to Pay',
    'select_student_search': 'Search & Select Student',
    'type_student_name_search': 'Type student name to search...',
    'registration_fee': 'Registration Fee',
    'transportation_fee': 'Transportation Fee',
    'uniform_fee': 'Uniform Fee',
    'tuition_fee': 'Tuition Fee',
    'books_materials': 'Books & Materials',
    'activities_fee': 'Activities Fee',
    'custom_invoice_title': 'Custom Invoice Title',
    'graduation_ceremony_fee': 'Graduation Ceremony Fee',
    'description_notes': 'Description / Notes',
    'bus_fee_term_1': 'e.g. Bus Fee - Term 1, Uniform Set, Registration Fees, etc.',
    'generate_new_fee_request': 'Generate a new fee request for a student.',
    'general_invoice_option': 'General Invoice (Not linked to any student)',
    'category_type': 'Category / Type',
    'select_category_structure': 'Select Category or Structure...',
    'standard_categories': 'Standard Categories',
    'academic_grade_structures': 'Academic Grade Structures',
    'other_custom_title': 'Other / Custom Title...',
    'custom_invoice_title_label': 'Custom Invoice Title',
    'total_amount': 'Total Amount',
    'void': 'Void',
    'grade_fee_structures': 'Grade Fee Structures',
    'add_grade_structure': 'Add Grade Structure',
    'edit_grade_structure': 'Edit Grade Structure',
    'update_base_amount_grade': 'Update the base amount for this grade.',
    'define_new_base_fee': 'Define a new base fee structure for a grade.',
    'grade_name': 'Grade Name',
    'grade_1_placeholder': 'e.g. Grade 1',
    'base_tuition_amount': 'Base Tuition Amount ($)',
    'update_structure': 'Update Structure',
    'add_structure': 'Add Structure',
    'delete_grade_structure': 'Delete Grade Structure',
    'delete_grade_structure_confirm': 'Are you sure you want to delete this grade structure? This will not affect existing invoices.',
    'expenses_management_desc': 'Manage school expenses and payroll payouts',
    'record_expense': 'Record Expense',
    'no_expenses_recorded': 'No expenses recorded yet.',
    'maintenance': 'Maintenance',
    'supplies': 'Supplies',
    'utilities': 'Utilities',
    'miscellaneous': 'Miscellaneous',
    'record': 'Record',
    'my_profile': 'My Profile',
    'access_credentials_desc': 'Access your credentials, academic details, and documents.',
    'no_associated_profiles': 'No associated student profiles found. Please contact administration.',
    'directory': 'Directory',
    'promotions': 'Promotions',
    'bulk': 'Bulk Operations',
    'bulk_assignment': 'Bulk assignment',
    'history': 'History',
    'loading_profile': 'Loading profile...',
    'student_id_card_export': 'Student ID Card Export',
    'student_identity_card': 'Student Identity Card',
    'smart_school_portal': 'Smart School Portal',
    'smart_school_management': 'Smart School Management',
    'export_id_card': 'Export ID Card',
    'valid': 'VALID',
    'birth_date': 'Birth Date',
    'print_export': 'Print / Export',
    'grade_student': 'Grade Student',
    'gender_label': 'Gender',
    'all_genders': 'All Genders',
    'all_years': 'All Years',
    'parent_guardian_search': 'Parent / Guardian Search',
    'type_to_search_parent': 'Type to search parent...',
    'na': 'N/A',
    'student_promotions': 'Student Promotions',
    'student_promotions_desc': 'Manage and approve student grade promotions for the upcoming academic year.',
    'promote_selected': 'Promote Selected ({count})',
    'all_school': 'All School',
    'by_grade': 'By Grade',
    'force_promotions_override': 'Force Promotions Override',
    'current_grade': 'Current Grade',
    'exam_status': 'Exam Status',
    'promote_to': 'Promote To',
    'not_applicable': 'Not Applicable',
    'not_yet_promoted': 'Not Yet Promoted',
    'demoted': 'Demoted',
    'passed': 'Passed',
    'successfully_promoted': 'Successfully promoted {count} students',
    'failed_to_promote': 'Failed to promote students',
    'please_select_students_promote': 'Please select students to promote',
    'graduated': 'Graduated',
    'fee_assignment': 'Fee Assignment',
    'messaging': 'Messaging',
    'registry_sync': 'Registry Sync',
    'select_fee_item': 'Select Fee Item',
    'choose_fee': '-- Choose Fee --',
    'payment_due_date': 'Payment Due Date',
    'assign_to_count': 'Assign to {count} Students',
    'subject_title': 'Subject / Title',
    'push_alert': 'Push Alert',
    'email_alert': 'Email Alert',
    'compose_message': 'Compose message...',
    'send_to_count': 'Send to {count}',
    'registry_auth_sync': 'Registry Authentication Sync',
    'registry_sync_desc': 'This tool ensures all selected students have valid Supabase Auth credentials. Use this to fix login issues for students added manually or before the latest system updates.',
    'start_credential_sync': 'Start Credential Sync',
    'please_select_students_fee': 'Please select students and a fee item',
    'assigned_fee_to_count': 'Assigned {fee} to {count} students',
    'failed_to_assign_fees': 'Failed to assign fees',
    'please_complete_all_fields': 'Please complete all fields',
    'message_sent_to_count': 'Message sent to {count} students',
    'failed_to_send_messages': 'Failed to send messages',
    'please_select_students_sync': 'Please select students to sync',
    'failed_to_sync_auth': 'Failed to sync authentication',
    'automated_notification_footer': 'This is an automated notification from your school system.',
    'fetching_registry': 'Fetching Registry...',
    'no_students_matched': 'No students matched the criteria.',
    'selected_count_students_batch': 'Selected {count} students for batch operation.',
    'sync_count_students': 'Sync {count} Students',
    'student_id_label': 'Student ID',
    'please_fix_errors_form': 'Please fix the errors in the form',
    'validation_error': 'Validation Error',
    'student_updated_success': 'Student updated successfully',
    'failed_to_generate_student_id': 'Failed to generate Student ID. Please try again.',
    'student_id_missing': 'Student ID is missing. Please close and reopen the form.',
    'database_schema_error': 'Database Schema Error',
    'registration_failed': 'Registration Failed',
    'student_registered_success': 'Student registered successfully',
    'student_added_to_grade': '{name} has been added to {grade}.',
    'failed_to_register_student': 'Failed to register student',
    'parent_email_address': 'Parent Email Address',
    'registration_finance_details': 'Registration & Finance Details',
    'date_of_joining': 'Date of Joining (Proration)',
    'joining_date_desc': 'Leave empty to use start of academic year.',
    'sibling_discount_scholarship': 'Sibling Discount / Scholarship (%)',
    'discount_placeholder': 'e.g. 15 for 15% discount',
    'fee_structure': 'Fee Structure',
    'select_grade_fee_structure': 'Select Grade Fee Structure',
    'select_fee_structure_option': 'Select Fee Structure',
    'custom_fees_amount': 'Custom fees amount',
    'manual_amount': 'Manual Amount ($)',
    'select_payment_structure': 'Select Payment Structure',
    'term_payment_installment': '{count} term payment ({count} installments)',
    'confirm_delete_document': 'Are you sure you want to delete this document?',
    'document_uploaded_success': 'Document uploaded successfully',
    'document_deleted_success': 'Document deleted successfully',
    'generating_pdf_invoice': 'Generating PDF invoice...',
    'invoice_pdf_downloaded_success': 'Invoice PDF downloaded successfully',
    'failed_download_pdf_invoice': 'Failed to download PDF invoice',
    'school_finance_department': 'School Finance Department',
    'official_academic_tuition_bill': 'Official Academic Tuition Bill',
    'billed_to': 'Billed To',
    'important_dates': 'Important Dates',
    'general_tuition_installment': 'General Tuition Installment',
    'subtotal': 'Subtotal',
    'discounts': 'Discounts',
    'amount_due_label': 'Amount Due',
    'thank_you_payment_contact': 'Thank you for your payment. For inquiries, please contact finance@school.edu',
    'generated_automatically_on': 'Generated automatically on',
    'tapped_transaction_details_desc': 'Tapped transactions details are shown dynamically',
    'classes_grading_ledgers': 'Classes & Grading Ledgers',
    'select_roster_desc': 'Select an active registration roster below to record grades, assign assessment links, or output printed cards.',
    'teacher_portal_mode': 'Teacher Portal Mode',
    'capacity_label': 'Capacity',
    'open_academic_ledger': 'Open Academic Ledger',
    'assigned_label': 'Assigned',
    'observe_only': 'Observe Only',
    'no_classes_configured': 'No Classes Configured Yet',
    'roster_database': 'Roster Database',
    'roster_database_desc': 'Submit individual student scores, manage subject sheets, and export grade matrixes.',
    'monthly_exams': 'Monthly Exams',
    'publish_term': 'Publish Term',
    'unpublish_term': 'Unpublish Term',
    'export_all_reports': 'Export All Reports',
    'by_student': 'By Student',
    'by_subject': 'By Subject',
    'search_academic_courses': 'Search academic courses...',
    'roster_name': 'Roster Name',
    'academic_state': 'Academic State',
    'published_label': 'Published',
    'confidential_label': 'Confidential',
    'preview_print': 'Preview Print',
    'grade_entry': 'Grade Entry',
    'subject_scheme': 'Subject Scheme',
    'assigned_instructor': 'Assigned Instructor',
    'available_admin_access': 'Available (Admin Access)',
    'grade_all_students': 'Grade All Students',
    'roll_label': 'Roll',
    'teacher_grading_notice': 'As a teacher, you can only edit grades for subjects assigned to you in the class schedule. Locked courses display a padlock indicator.',
    'admin_grading_notice': 'As an Administrator, you have full override control across all subjects in the registry.',
    'assigned_to_you': 'Assigned to You',
    'staff_assigned': 'Staff Assigned',
    'lock_label': 'Lock',
    'score_placeholder': 'Score',
    'score_exceeds_error': 'Score exceeds scale! Limit is',
    'public_comments_placeholder': 'Public Report Card Comments...',
    'internal_remarks_placeholder': 'Internal remarks (optional)...',
    'link_exam': 'Link Exam',
    'submit_assessment_scores': 'Submit Assessment Scores',
    'grading_sheet': 'Grading Sheet',
    'no_students_registered': 'No active student directories registered inside',
    'feedback_remarks_placeholder': 'Feedback / Remarks...',
    'update_all_scores_notice': 'This updates {subjectName} scores for all registered rows concurrently.',
    'update_courses_spreadsheet': 'Update Courses Spreadsheet',
    'final_percentage_label': 'Final %',
    'final_grade_label': 'Final Grade',
    'final_rank_label': 'Final Rank',
    'no_records_found': 'No Student Records Found',
    'no_student_credentials_desc': 'There are no student accounts currently associated with your credentials.',
    'document_printing_desk': 'Document Printing Desk',
    'printing_desk_desc': 'Toggle layouts and configure printer options.',
    'single_period_card': 'Single Period Card',
    'annual_progress_report': 'Annual Progress Report',
    'print_save_pdf': 'Print / Save PDF',
    'close_drawer': 'Close Drawer',
    'awaiting': 'Awaiting',
    'consistently_responsive_feedback': 'Consistently responsive in routine learning drills.',
    'compiling': 'Compiling...',
    '1st_term': '1st Term',
    '2nd_term': '2nd Term',
    'final_exam': 'Final Exam',
    'class_rank': 'Class Rank',
    'aggregating_records': 'Aggregating records indices...',
    'official_academic_performance': 'Official Academic Performance Credentials',
    'student_label': 'Student',
    'roll_no_label': 'Roll No',
    'academic_term_label': 'Academic Term',
    'course_catalog': 'Course Catalog',
    'max_scale': 'Max Scale',
    'score_obtained': 'Score Obtained',
    'letter_grade': 'Letter Grade',
    'instructor_feedback': 'Instructor Feedback',
    'admin_eval_legend': 'Administrative Evaluation Index Legend',
    'academic_attendance': 'Academic Attendance',
    'total_days': 'Total days',
    'attended': 'Attended',
    'absent_label': 'Absent',
    'calculating_records': 'Calculating registry records...',
    'performance_standing': 'Performance Standing',
    'teacher_endorsement': 'Teacher Endorsement',
    'admin_registrar': 'Administrative Registrar',
    'annual_progress_credentials': 'Annual Progress & Performance Credentials',
    'year_label': 'Year',
    'obtained_label': 'Obtained',
    'mo_avg': 'Mo. Avg',
    'performance_eval_summary': 'Performance Evaluation Summary',
    'overall_term_percentile': 'Overall Term Percentile',
    'class_standing': 'Class Standing',
    'school_attendance': 'School Attendance',
    'registrar_credentials': 'Registrar Credentials',
    'registrar_cert_text': 'This certifies that {name} has concluded the corresponding class curriculum requirements with proper active registration.',
    'registrar_signature': 'Registrar Signature',
    'principal_signature': 'Principal signature',
    'return_to_dashboard': 'Return to Dashboard',
  },
  ar: {
    'dashboard': 'لوحة القيادة',
    'academics': 'الأكاديميين',
    'students': 'الطلاب',
    'parent': 'ولي أمر',
    'report_cards': 'كشوف الدرجات',
    'exams': 'التقييمات',
    'schedule': 'الجدول الزمني',
    'attendance': 'الحضور',
    'visitors': 'الزوار',
    'inventory': 'المخزون',
    'fees': 'الرسوم والمدفوعات',
    'hr': 'الموارد البشرية',
    'transport': 'النقل',
    'analytics': 'التحليلات',
    'communication': 'الإشعارات',
    'settings': 'الإعدادات',
    'notifications': 'التنبيهات',
    'switch_language': 'تغيير اللغة',
    'toggle_theme': 'تغيير المظهر',
    'sign_out': 'تسجيل الخروج',
    'search': 'بحث...',
    'welcome': 'مرحباً بعودتك',
    'close_profile': 'إغلاق الملف الشخصي',
    'view_all_notifications': 'عرض جميع التنبيهات',
    'new': 'جديد',
    'add': 'إضافة',
    'edit': 'تعديل',
    'delete': 'حذف',
    'save': 'حفظ',
    'cancel': 'إلغاء',
    'actions': 'إجراءات',
    'status': 'الحالة',
    'name': 'الاسم',
    'date': 'التاريخ',
    'description': 'الوصف',
    'category': 'الفئة',
    'active': 'نشط',
    'inactive': 'غير نشط',
    'upcoming': 'قادم',
    'overview': 'نظرة عامة',
    'assessments': 'التقييمات',
    'payments': 'المدفوعات',
    'no_assessments': 'لم يتم العثور على تقييمات لهذا الطالب',
    'no_payments': 'لم يتم العثور على سجلات دفع لهذا الطالب',
    'due_date': 'تاريخ الاستحقاق',
    'amount': 'المبلغ',
    'academic_years': 'السنوات الأكاديمية',
    'classes': 'الفصول',
    'subjects': 'المواد الدراسية',
    'manage': 'إدارة',
    'total': 'الإجمالي',
    'view': 'عرض',
    'loading': 'جاري التحميل...',
    'no_data': 'لا توجد بيانات',
    'success': 'تم بنجاح',
    'error': 'خطأ',
    'confirm_delete': 'هل أنت متأكد أنك تريد حذف هذا؟',
    'delete_confirmation': 'هل أنت متأكد؟',
    'delete_fee_item_warning': 'سيؤدي هذا الإجراء إلى حذف هذا البند نهائياً من الهيكل القياسي. لن تتأثر الفواتير الحالية.',
    'inventory_desc': 'إدارة أصول ومعدات المدرسة.',
    'visitors_desc': 'إدارة زوار الحرم المدرسي وتسجيل الدخول.',
    'academics_desc': 'إدارة السنوات الأكاديمية والفصول والمواد.',
    'student_id': 'رقم الطالب',
    'grade': 'الصف',
    'section': 'القسم',
    'all_grades': 'جميع الصفوف',
    'male': 'ذكر',
    'female': 'أنثى',
    'phone': 'الهاتف',
    'email': 'البريد الإلكتروني',
    'address': 'العنوان',
    'parent_name': 'اسم ولي الأمر',
    'relation': 'العلاقة',
    'purpose': 'الغرض',
    'host': 'المضيف',
    'time_in': 'وقت الدخول',
    'time_out': 'وقت الخروج',
    'check_in': 'تسجيل دخول',
    'check_out': 'تسجيل خروج',
    'asset_name': 'اسم الأصل',
    'assigned_to': 'مخصص لـ',
    'asset': 'أصل',
    'none': 'لا يوجد',
    'account': 'الحساب',
    'no_notifications': 'لا توجد تنبيهات جديدة',
    'across_all_grades': 'عبر جميع الصفوف',
    'password': 'كلمة المرور',
    'forgot_password': 'هل نسيت؟',
    'sign_in_to_dashboard': 'تسجيل الدخول',
    'mvp_quick_login': 'دخول سريع للتجربة',
    'built_with_love': 'صُنع بحب ❤️ بواسطة AwoodaTech™',
    'active_curriculum': 'المنهج النشط',
    'no_permission': 'ليس لديك صلاحية لعرض هذه الصفحة.',
    'welcome_back': 'مرحباً بعودتك',
    'school_status_desc': 'إليك ما يحدث في مدرستك اليوم.',
    'total_students': 'إجمالي الطلاب',
    'attendance_today': 'حضور اليوم',
    'fees_collected': 'الرسوم المحصلة',
    'pending_dues': 'المستحقات المعلقة',
    'recent_activity': 'النشاط الأخير',
    'quick_actions': 'إجراءات سريعة',
    'register_student': 'تسجيل طالب',
    'manage_fees': 'إدارة الرسوم',
    'urgent_alerts': 'تنبيهات عاجلة',
    'no_urgent_alerts': 'لا توجد تنبيهات عاجلة.',
    'hello': 'مرحباً',
    'classes_today': 'لديك {count} فصول اليوم.',
    'take_attendance': 'تسجيل الحضور',
    'attendance_rate': 'نسبة الحضور',
    'upcoming_tasks': 'المهام القادمة',
    'todays_schedule': 'جدول اليوم',
    'view_full_schedule': 'عرض الجدول الكامل',
    'mark_attendance': 'رصد الحضور',
    'post_notice': 'نشر إعلان',
    'add_assessment': 'إضافة تقييم',
    'recent_notices': 'الإعلانات الأخيرة',
    'no_recent_notices': 'لا توجد إعلانات أخيرة.',
    'financial_overview': 'نظرة مالية عامة لليوم.',
    'collected_today': 'المحصل اليوم',
    'pending_fees': 'الرسوم المعلقة',
    'record_payment': 'تسجيل دفعة جديدة',
    'latest_update_child': 'إليك آخر التحديثات لطفلك.',
    'student_profile': 'ملف الطالب',
    'upcoming_assignments': 'الواجبات القادمة',
    'due': 'مستحق',
    'posted': 'نشر في',
    'by': 'بواسطة',
    'students_directory': 'دليل الطلاب',
    'students_directory_desc': 'البحث عن معلومات الاتصال والملفات الشخصية المفصلة للطلاب وأولياء الأمور.',
    'add_student': 'إضافة طالب',
    'grade_cards': 'بطاقات الدرجات',
    'filters': 'الفلاتر',
    'search_students': 'البحث عن طلاب...',
    'student': 'طالب',
    'roll_number': 'رقم القيد',
    'no_students_found': 'لم يتم العثور على طلاب.',
    'previous': 'السابق',
    'next': 'التالي',
    'page_of': 'صفحة {page} من {total}',
    'dropped_deleted_students': 'الطلاب المنسحبون والمحذوفون',
    'search_history': 'البحث في السجل...',
    'reason': 'السبب',
    'restore': 'استعادة',
    'classes_grades': 'الفصول / الصفوف',
    'classes_grades_desc': 'اختر فصلاً لإدخال درجات طلابه.',
    'select_grade': 'اختر الصف',
    'open_register': 'فتح السجل',
    'promote_by_grade': 'الترقية حسب الصف',
    'promote_by_grade_desc': 'ترقية جماعية لجميع الطلاب في صف معين إلى المستوى التالي.',
    'start_promotion': 'بدء الترقية',
    'promote_by_class': 'الترقية حسب الفصل',
    'promote_by_class_desc': 'ترقية الطلاب من قسم فصل معين.',
    'manual_promotion': 'ترقية يدوية',
    'manual_promotion_desc': 'اختيار طلاب فرادى للترقية يدوياً.',
    'promote_students': 'ترقية الطلاب',
    'promote_students_grade_desc': 'ترقية الطلاب حسب مستوى الصف',
    'promote_students_class_desc': 'ترقية الطلاب حسب قسم الفصل',
    'promote_students_manual_desc': 'اختيار الطلاب يدوياً للترقية',
    'select_current_grade': 'اختر الصف الحالي',
    'select_current_class': 'اختر الفصل الحالي',
    'search_student': 'البحث عن طالب',
    'search_student_placeholder': 'البحث عن اسم الطالب أو الرقم...',
    'target_grade': 'الصف المستهدف (الترقية إلى)',
    'select_target_grade': 'اختر الصف المستهدف',
    'graduated_completed': 'تخرج / اكتمل',
    'promotion_warning': 'ستؤدي ترقية الطلاب إلى تحديث صفهم الحالي وعامهم الأكاديمي. سيؤدي هذا الإجراء أيضاً إلى إنشاء سجل التحاق جديد للدورة القادمة.',
    'classes_sections': 'الفصول والأقسام',
    'curriculum_subjects': 'مواد المنهج',
    'add_year': 'إضافة عام',
    'add_class': 'إضافة فصل',
    'add_subject': 'إضافة مادة',
    'edit_year': 'تعديل العام الأكاديمي',
    'edit_class': 'تعديل الفصل',
    'edit_subject': 'تعديل المادة',
    'year_name': 'اسم العام',
    'start_date': 'تاريخ البدء',
    'end_date': 'تاريخ الانتهاء',
    'subject_name': 'اسم المادة',
    'subject_code': 'رمز المادة',
    'gradebook': 'سجل الدرجات',
    'submissions': 'التسليمات',
    'all_assessments': 'جميع التقييمات',
    'new_assessment': 'تقييم جديد',
    'assessment_title': 'عنوان التقييم',
    'max_score': 'الدرجة القصوى',
    'view_submissions': 'عرض التسليمات',
    'grade_now': 'رصد الدرجات الآن',
    'select_class': 'اختر الفصل',
    'select_subject': 'اختر المادة',
    'select_assessment_to_grade': 'اختر التقييم لرصد الدرجات',
    'save_grades': 'حفظ الدرجات',
    'student_name': 'اسم الطالب',
    'feedback': 'الملاحظات',
    'roll': 'رقم القيد',
    'back_to_list': 'العودة للقائمة',
    'instructions': 'التعليمات',
    'homework': 'واجب منزلي',
    'assignment': 'تكليف',
    'online_exam': 'امتحان أونلاين',
    'offline_exam': 'امتحان ورقي',
    'exam_date': 'تاريخ الامتحان',
    'grading': 'رصد الدرجات',
    'remember_to_save': 'تذكر الحفظ قبل المغادرة',
    'my_assignments': 'تكليفاتي',
    'past_results': 'النتائج السابقة',
    'current_gpa': 'المعدل التراكمي الحالي',
    'top_class': 'من أفضل 10% في الصف',
    'total_credits': 'إجمالي الساعات',
    'absences': 'الغيابات',
    'subject_breakdown': 'تفاصيل المواد',
    'term_1': 'الفصل الدراسي الأول',
    'todo': 'للقيام به',
    'in_progress': 'قيد التنفيذ',
    'completed': 'مكتمل',
    'academic_report': 'التقرير الأكاديمي',
    'viewing_performance_for': 'عرض الأداء لـ',
    'update_academic_year_desc': 'تحديث تفاصيل العام الأكاديمي.',
    'create_academic_year_desc': 'إنشاء فترة عام أكاديمي جديدة.',
    'update_class_desc': 'تحديث تفاصيل الفصل.',
    'create_class_desc': 'إنشاء قسم فصل جديد.',
    'update_subject_desc': 'تحديث تفاصيل المادة.',
    'create_subject_desc': 'إنشاء مادة جديدة للمنهج.',
    'attendance_history': 'سجل الحضور',
    'attendance_history_desc': 'مراجعة سجلات الحضور السابقة لفصولك.',
    'back_to_marking': 'العودة للتحضير',
    'no_history_found': 'لم يتم العثور على سجل حضور.',
    'students_marked': 'طلاب تم تحضيرهم',
    'no_students_attendance_desc': 'لا يوجد طلاب مسجلون في العام الأكاديمي الحالي. يرجى إضافة طلاب أولاً.',
    'marked': 'تم تحضيرهم',
    'please_mark_all': 'يرجى تحضير جميع الطلاب',
    'saved_successfully': 'تم الحفظ بنجاح',
    'submit_attendance': 'إرسال التحضير',
    'overview_dashboard': 'لوحة التحكم العامة',
    'mark_all_present': 'تحضير الجميع كحاضر',
    'all_classes': 'جميع الفصول',
    'attendance_details': 'تفاصيل تحضير اليوم',
    'loading_details': 'جاري تحميل التفاصيل...',
    'no_grade': 'بدون صف',
    'marked_all_present_toast': 'تم تحديد جميع الطلاب غير المحضرين كحاضرين',
    'attendance_record': 'سجل الحضور',
    'viewing_records_for': 'عرض السجلات لـ',
    'your_student': 'طالبك',
    'present': 'حاضر',
    'absent': 'غائب',
    'late': 'متأخر',
    'excused': 'بعذر',
    'view_history': 'عرض السجل',
    'overall_attendance_for': 'إجمالي الحضور لـ',
    'late_arrivals': 'وصول متأخر',
    'unmarked': 'غير محضر',
    'class_breakdown': 'تفاصيل الفصول',
    'no_class_data': 'لا توجد بيانات للفصول.',
    'pending': 'قيد الانتظار',
    'attendance_history_all_desc': 'السجلات اليومية للمدرسة بأكملها.',
    'search_by_date': 'البحث بالتاريخ...',
    'close': 'إغلاق',
    'add_asset': 'إضافة أصل',
    'asset_details': 'تفاصيل الأصل',
    'next_maintenance': 'الصيانة القادمة',
    'no_assets_found': 'لم يتم العثور على أصول.',
    'page': 'صفحة',
    'of': 'من',
    'add_new_asset': 'إضافة أصل جديد',
    'add_asset_desc': 'تسجيل عنصر جديد في مخزون المدرسة.',
    'laptop': 'كمبيوتر محمول',
    'projector': 'جهاز عرض',
    'sports_equipment': 'معدات رياضية',
    'furniture': 'أثاث',
    'next_maintenance_date': 'تاريخ الصيانة القادمة',
    'new_check_in': 'تسجيل دخول جديد',
    'visitor': 'زائر',
    'purpose_host': 'الغرض والمضيف',
    'time': 'الوقت',
    'no_visitors_found': 'لم يتم العثور على زوار.',
    'new_visitor_checkin': 'تسجيل دخول زائر جديد',
    'new_visitor_desc': 'تسجيل زائر جديد وطباعة بطاقته.',
    'full_name': 'الاسم الكامل',
    'purpose_of_visit': 'الغرض من الزيارة',
    'host_staff_member': 'المضيف (موظف)',
    'check_in_print': 'تسجيل الدخول وطباعة البطاقة',
    'dropped_out': 'منسحب',
    'transferred': 'منقول',
    'delete_student': 'حذف طالب',
    'delete_student_desc': 'سيؤدي هذا إلى حذف سجل الطالب مؤقتاً.',
    'reason_for_deletion': 'سبب الحذف',
    'delete_reason_placeholder': 'مثلاً: متخرج، منسحب، منقول...',
    'update_student_details': 'تحديث تفاصيل الطالب',
    'register_new_student': 'تسجيل طالب جديد',
    'modify_student_info': 'تعديل معلومات الطالب الحالية.',
    'add_new_student_desc': 'إضافة طالب جديد إلى قاعدة بيانات المدرسة.',
    'student_id_auto': 'رقم الطالب (مولد تلقائياً)',
    'other': 'آخر',
    'residential_address': 'عنوان السكن',
    'enter_address_placeholder': 'أدخل العنوان الكامل...',
    'parent_guardian_info': 'معلومات ولي الأمر/الوصي',
    'parent_name_search': 'اسم ولي الأمر (قابل للبحث)',
    'search_parent_placeholder': 'ابحث أو أدخل الاسم...',
    'relation_to_student': 'العلاقة بالطالب',
    'father': 'أب',
    'mother': 'أم',
    'guardian': 'وصي',
    'brother': 'أخ',
    'sister': 'أخت',
    'parent_phone': 'هاتف ولي الأمر',
    'predefined': 'محدد مسبقاً',
    'manual_entry': 'إدخال يدوي',
    'select_predefined_structure': 'اختر هيكلاً محدداً مسبقاً',
    'select_fee_structure': 'اختر هيكل الرسوم',
    'add_fee_item': 'إضافة بند رسوم',
    'item_name': 'اسم البند',
    'frequency': 'التكرار',
    'per_term': 'لكل فصل دراسي',
    'monthly': 'شهرياً',
    'annual': 'سنوياً',
    'one_time': 'مرة واحدة',
    'academic': 'أكاديمي',
    'extracurricular': 'أنشطة إضافية',
    'facility': 'مرافق',
    'additional_information': 'معلومات إضافية',
    'additional_info_placeholder': 'أي تفاصيل أخرى (طبية، حساسية، إلخ)...',
    'medical': 'طبي',
    'behavior': 'السلوك',
    'timeline': 'الجدول الزمني',
    'emergency_contact': 'جهة اتصال للطوارئ',
    'conditions': 'الحالات',
    'allergies': 'الحساسية',
    'none_listed': 'لا يوجد',
    'no_known_allergies': 'لا توجد حساسية معروفة',
    'no_medical_records': 'لا توجد سجلات طبية متاحة.',
    'total_merits': 'إجمالي المزايا',
    'total_demerits': 'إجمالي العيوب',
    'recent_records': 'السجلات الأخيرة',
    'no_behavior_records': 'لم يتم العثور على سجلات سلوك.',
    'award': 'جائزة',
    'file': 'ملف',
    'fee_management': 'إدارة الرسوم',
    'fee_management_desc': 'تتبع وتسجيل مدفوعات الطلاب.',
    'new_invoice': 'فاتورة جديدة',
    'collected': 'المحصلة',
    'overdue': 'متأخرة',
    'search_invoices_placeholder': 'البحث باسم الطالب أو رقم الفاتورة...',
    'all': 'الكل',
    'structure': 'الهيكل',
    'standard_fee_items': 'بنود الرسوم القياسية',
    'no_invoices_found': 'لم يتم العثور على فواتير.',
    'edit_fee_item': 'تعديل بند رسوم',
    'update_fee_item_desc': 'تحديث تفاصيل هذا الرسم القياسي.',
    'add_fee_item_desc': 'تعريف رسم قياسي جديد للمدرسة.',
    'update_item': 'تحديث البند',
    'total_paid': 'إجمالي المدفوعات',
    'invoice_history': 'سجل الفواتير',
    'payment_method': 'طريقة الدفع',
    'cash': 'نقداً',
    'bank_transfer': 'تحويل بنكي',
    'cheque': 'شيك',
    'card': 'بطاقة',
    'reference_number': 'رقم المرجع',
    'void_invoice': 'إلغاء الفاتورة',
    'create_new_invoice': 'إنشاء فاتورة جديدة',
    'generate_fee_request_desc': 'إنشاء طلب رسوم جديد لطالب.',
    'select_student': 'اختر الطالب',
    'select_student_placeholder': 'اختر طالباً...',
    'fee_item': 'بند الرسوم',
    'select_fee_type': 'اختر نوع الرسوم...',
    'custom_fee': 'رسوم مخصصة...',
    'communication_desc': 'إعلانات وإشعارات المدرسة.',
    'notice_board': 'لوحة الإعلانات',
    'direct_messages': 'الرسائل المباشرة',
    'broadcasts': 'البث',
    'new_notice': 'إعلان جديد',
    'important_announcement': 'إعلان هام',
    'everyone': 'الجميع',
    'parents_only': 'أولياء الأمور فقط',
    'staff_only': 'الموظفون فقط',
    'search_messages': 'البحث في الرسائل...',
    'type_message_placeholder': 'اكتب رسالتك...',
    'select_user_to_chat': 'اختر مستخدماً لبدء الدردشة',
    'urgent_broadcast': 'بث عاجل',
    'urgent_broadcast_desc': 'إرسال إشعارات فورية لأولياء الأمور والموظفين.',
    'delivery_method': 'طريقة التسليم',
    'whatsapp': 'واتساب',
    'app_push': 'إشعار تطبيق',
    'message_template': 'قالب الرسالة',
    'urgent_alert': 'تنبيه عاجل (معتمد مسبقاً)',
    'school_closure': 'إغلاق المدرسة (معتمد مسبقاً)',
    'event_reminder': 'تذكير بحدث',
    'custom_message': 'رسالة مخصصة (قد تتأخر)',
    'whatsapp_template_desc': 'يتطلب واتساب قوالب معتمدة مسبقاً للتسليم الفوري خارج نافذة الـ 24 ساعة.',
    'notification_priority': 'أولوية الإشعار',
    'high_priority_desc': 'عالية (تتجاوز وضع عدم الإزعاج)',
    'normal_priority': 'عادية',
    'email_subject': 'موضوع البريد الإلكتروني',
    'target_audience': 'الجمهور المستهدف',
    'entire_school': 'المدرسة بأكملها (أولياء أمور وموظفون)',
    'all_parents': 'جميع أولياء الأمور',
    'all_staff': 'جميع الموظفين',
    'grade4_parents': 'أولياء أمور الصف الرابع فقط',
    'message_content': 'محتوى الرسالة',
    'type_urgent_message': 'اكتب رسالتك العاجلة هنا...',
    'whatsapp_concise_desc': 'اجعلها موجزة للواتساب.',
    'message_length_limit': 'حد طول الرسالة.',
    'send_broadcast_now': 'إرسال البث الآن',
    'post_new_notice': 'نشر إعلان جديد',
    'broadcast_message_desc': 'بث رسالة لمجتمع المدرسة.',
    'mark_as_important': 'تحديد كـ هام',
    'create_invoice': 'إنشاء فاتورة',
    'fees_payments': 'الرسوم والمدفوعات',
    'manage_payments_for': 'إدارة المدفوعات لـ',
    'total_amount_due': 'إجمالي المبلغ المستحق',
    'pay_now': 'ادفع الآن',
    'assigned_fee_structure': 'هيكل الرسوم المخصص',
    'invoice': 'فاتورة',
    'pay': 'دفع',
    'payment_successful': 'تم الدفع بنجاح',
    'payment_processed_desc': 'تمت معالجة دفعتك وإنشاء إيصال.',
    'failed_to_process_payment': 'فشل في معالجة الدفعة',
    'locale': 'ar-SA',
    'urgent_alert_template': 'تنبيه عاجل (معتمد مسبقاً)',
    'school_closure_template': 'إغلاق المدرسة (معتمد مسبقاً)',
    'event_reminder_template': 'تذكير بحدث',
    'custom_message_template': 'رسالة مخصصة (قد تتأخر)',
    'whatsapp_template_notice': 'يتطلب واتساب قوالب معتمدة مسبقاً للتسليم الفوري خارج نافذة الـ 24 ساعة.',
    'email_subject_placeholder': 'مثلاً: عاجل: إغلاق المدرسة غداً',
    'grade_4_parents': 'أولياء أمور الصف الرابع فقط',
    'urgent_message_placeholder': 'اكتب رسالتك العاجلة هنا...',
    'whatsapp_concise': 'اجعلها موجزة للواتساب.',
    'chars': 'حرف',
    'post_new_notice_desc': 'نشر رسالة لمجتمع المدرسة.',
    'notice_title_placeholder': 'مثلاً: تغيير موعد اليوم الرياضي',
    'notice_content_placeholder': 'اكتب إعلانك هنا...',
    'urgent': 'عاجل',
    'broadcast_sent_success': 'تم إرسال البث بنجاح لجميع المستلمين المختارين.',
    'failed_to_send_broadcast': 'فشل في إرسال البث',
    'notice_posted_success': 'تم نشر الإعلان بنجاح',
    'failed_to_post_notice': 'فشل في نشر الإعلان',
    'failed_to_send_message': 'فشل في إرسال الرسالة',
    'submissions_for': 'التسليمات: {title}',
    'go_to_gradebook': 'الذهاب إلى سجل الدرجات',
    'submitted_today': 'تم التسليم اليوم',
    'submitted_yesterday': 'تم التسليم أمس',
    'review_submission': 'مراجعة التسليم',
    'graded_on': 'تم رصد الدرجة في {date}',
    'assessment_label': 'التقييم',
    'student_work': 'عمل الطالب',
    'no_content_provided': 'لم يتم تقديم محتوى.',
    'grade_score_max': 'الدرجة / النتيجة (الأقصى: {max})',
    'enter_score': 'أدخل الدرجة...',
    'needs_revision': 'يحتاج إلى مراجعة',
    'feedback_for_student': 'ملاحظات للطالب',
    'provide_feedback_placeholder': 'قدم ملاحظات بناءة...',
    'submit_grade': 'إرسال الدرجة',
    'could_not_identify_student': 'تعذر تحديد الطالب',
    'assignment_submitted_success': 'تم تسليم التكليف بنجاح!',
    'failed_to_submit_assignment': 'فشل في تسليم التكليف',
    'complete_percentage': 'اكتمل بنسبة {percentage}%',
    'pending_grading': 'في انتظار رصد الدرجات',
    'no_instructions_provided': 'لا توجد تعليمات إضافية مقدمة.',
    'your_work': 'عملك',
    'uploading': 'جاري الرفع...',
    'click_to_upload': 'انقر للرفع أو اسحب وأفلت',
    'upload_limits': 'PDF، DOCX، PPTX، أو صور (بحد أقصى 10 ميجابايت)',
    'private_comment_placeholder': 'أضف تعليقاً خاصاً لمعلمك...',
    'mark_as_done': 'تحديد كمكتمل',
    'teacher_feedback': 'ملاحظات المعلم',
    'score_label': 'الدرجة',
    'class_name': 'اسم الفصل',
    'academic_year': 'العام الأكاديمي',
    'attendance_saved_desc': 'تم تسجيل الحضور لـ {count} طالباً.',
    'failed_to_save_attendance': 'فشل في حفظ الحضور',
    'attendance_saved_success': 'تم حفظ الحضور بنجاح',
    'online_exams': 'الامتحانات عبر الإنترنت',
    'exams_student_desc': 'عرض وأداء التقييمات الخاصة بك',
    'exams_admin_desc': 'إدارة الامتحانات والتقييمات عبر الإنترنت',
    'create_exam': 'إنشاء امتحان',
    'search_exams_placeholder': 'البحث عن الامتحانات بالعنوان أو المادة...',
    'all_status': 'كل الحالات',
    'live_now': 'مباشر الآن',
    'no_exams_found': 'لم يتم العثور على امتحانات.',
    'minutes': 'دقائق',
    'questions': 'أسئلة',
    'marks': 'درجات',
    'start_exam': 'بدء الامتحان',
    'monitor_live': 'مراقبة مباشرة',
    'starts_soon': 'يبدأ قريباً',
    'view_results': 'عرض النتائج',
    'view_analytics': 'عرض التحليلات',
    'page_label': 'صفحة',
    'of_label': 'من',
    'total_label': 'الإجمالي',
    'create_new_exam': 'إنشاء امتحان جديد',
    'exam_create_desc': 'تكوين تفاصيل الامتحان وإضافة الأسئلة',
    'save_exam': 'حفظ الامتحان',
    'saving': 'جاري الحفظ...',
    'exam_settings_step': '1. إعدادات الامتحان',
    'questions_step': '2. الأسئلة',
    'exam_title_label': 'عنوان الامتحان',
    'exam_title_placeholder': 'مثلاً: رياضيات منتصف الفصل',
    'target_grade_label': 'الصف المستهدف',
    'assessment_type_label': 'نوع التقييم',
    'duration_minutes_label': 'المدة (بالدقائق)',
    'auto_calculated': '(محسوب تلقائياً)',
    'description_label': 'الوصف',
    'exam_desc_placeholder': 'أدخل تعليمات التقييم أو الوصف...',
    'continue_to_questions': 'المتابعة إلى الأسئلة',
    'add_question': 'إضافة سؤال',
    'question_details': 'تفاصيل السؤال',
    'question_text_label': 'نص السؤال',
    'question_text_placeholder': 'أدخل سؤالك هنا...',
    'question_type_label': 'نوع السؤال',
    'multiple_choice': 'اختيار من متعدد',
    'true_false': 'صح / خطأ',
    'multiple_response': 'إجابات متعددة (مربعات اختيار)',
    'short_answer': 'إجابة قصيرة (مطابقة تامة)',
    'marks_label': 'الدرجات',
    'options_correct_answer': 'الخيارات والإجابة الصحيحة',
    'option_label': 'خيار',
    'correct_answer_label': 'الإجابة الصحيحة',
    'true_label': 'صح',
    'false_label': 'خطأ',
    'short_answer_placeholder': 'أدخل الإجابة الصحيحة بدقة...',
    'short_answer_note': 'ملاحظة: يجب أن تتطابق استجابة الطالب مع هذا تماماً (يمكن تنفيذ فحص غير حساس لحالة الأحرف في منطق التصحيح).',
    'add_another_question': 'إضافة سؤال آخر',
    'active_year_not_found': 'لم يتم العثور على العام الأكاديمي النشط',
    'assessment_created_success': 'تم إنشاء التقييم بنجاح',
    'failed_to_create_assessment': 'فشل في إنشاء التقييم',
    'exam_submitted_success': 'تم تقديم الامتحان بنجاح!',
    'exam_submitted_desc': 'تم تسجيل إجاباتك. يمكنك عرض نتائجك بمجرد قيام المعلم بنشرها.',
    'answered': 'تمت الإجابة',
    'submit_exam': 'تقديم الامتحان',
    'submitting': 'جاري التقديم...',
    'question_label': 'سؤال',
    'flag_for_review': 'تحديد للمراجعة',
    'type_answer_placeholder': 'اكتب إجابتك هنا...',
    'question_navigator': 'متصفح الأسئلة',
    'unanswered': 'لم تتم الإجابة',
    'submit_exam_confirm': 'هل أنت متأكد أنك تريد تقديم امتحانك؟ لا يمكنك تغيير إجاباتك بعد التقديم.',
    'todays_attendance': 'حضور اليوم',
    'collection_gap': 'فجوة التحصيل',
    'revenue': 'الإيرادات',
    'pending_receivables': 'المستحقات المعلقة',
    'active_members': 'عضواً نشطاً',
    'publications': 'منشورات',
    'financial_pulse': 'النبض المالي',
    'revenue_analysis': 'تحليل الإيرادات مقابل المستحقات',
    'directives': 'التوجيهات',
    'no_active_directives': 'لا توجد توجيهات نشطة',
    'academic_trajectory': 'المسار الأكاديمي',
    'growth_in_progress': 'النمو قيد التقدم',
    'milestones_achieved': 'تم تحقيق جميع الأهداف الحالية بنجاح.',
    'live_presence': 'التواجد المباشر',
    'status_active': 'الحالة نشطة',
    'next_milestone': 'المرحلة القادمة',
    'take_task': 'بدء المهمة',
    'activity_logs': 'سجلات النشاط',
    'recent_audits': 'عمليات التدقيق والذكاء الأخيرة',
    'today_revenue': 'إيرادات اليوم',
    'staff_faculty': 'الموظفون وأعضاء هيئة التدريس',
    'live_notices': 'الإعلانات الحية',
    'student_enrolled': 'تم تسجيل طالب جديد',
    'staff_created': 'تم تعيين موظف جديد',
    'fee_invoice_generated': 'تم إنشاء فاتورة رسوم',
    'fee_invoice_voided': 'تم إلغاء فاتورة رسوم',
    'payment_recorded': 'تم تسجيل عملية دفع',
    'assessment_created': 'تم إنشاء تقييم جديد',
    'bulk_attendance_saved': 'تم حفظ الحضور الجماعي',
    'active_classes_count': 'فصول نشطة',
    'students_present_count': 'طلاب حاضرون',
    'today': 'اليوم',
    'ago': 'منذ',
    'm': 'د',
    'h': 'س',
    'd': 'ي',
    'engagement': 'التفاعل',
    'tasks': 'المهام',
    'classroom_intelligence': 'ذكاء الفصول الدراسية',
    'todays_agenda': 'جدول أعمال اليوم',
    'full_schedule': 'الجدول الكامل',
    'intelligence_feed': 'تحديثات الذكاء',
    'broadcast': 'بث',
    'no_classes_scheduled': 'لا توجد فصول مجدولة',
    'enjoy_prep_time': 'استمتع بوقت التحضير الخاص بك!',
    'total_ytd': 'إجمالي السنة حتى الآن',
    'outstanding': 'المبالغ المستحقة',
    'no_financial_directives': 'لا توجد توجيهات مالية',
    'run_invoice_audit': 'تشغيل تدقيق الفواتير',
    'configure_fee_tiers': 'تكوين فئات الرسوم',
    'security_note': 'ملاحظة أمنية',
    'payment_integrity_msg': 'جميع سجلات الدفع موقعة مشفراً ومدققة لضمان النزاهة.',
    'free_day': 'يوم راحة',
    'no_scheduled_classes': 'لا توجد دروس مجدولة اليوم.',
    'financial_command': 'القيادة المالية',
    'attendance_pulse': 'نبض الحضور',
    'daily_flow_stats': 'إحصائيات التدفق اليومي',
    'on_campus': 'في الحرم المدرسي',
    'operations_log': 'سجل العمليات',
    'live_feed': 'بث مباشر',
    'quick_hub': 'المركز السريع',
    'billing': 'الفواتير',
    'alert': 'تنبيه',
    'high_priority': 'أولوية قصوى',
    'no_critical_alerts': 'لا توجد تنبيهات ذات أولوية قصوى',
    'full_systems_audit': 'تدقيق كامل للنظام',
    'collected_label': 'المحصلة',
    'notifications_blocked': 'التنبيهات محظورة',
    'notifications_blocked_desc': 'يرجى إلغاء حظر التنبيهات من إعدادات المتصفح لتلقي التنبيهات المباشرة.',
    'online_sync': 'مزامنة مباشرة',
    'offline_local': 'وضع عدم الاتصال (محلي أولاً)',
    'publisher': 'الناشر',
    'audience': 'الجمهور',
    'open_notice_board': 'فتح لوحة الإعلانات',
    'system_online_msg': 'النظام متصل: المزامنة المباشرة نشطة',
    'offline_mode_msg': 'وضع عدم الاتصال: يتم تخزين البيانات محليًا وفي انتظار المزامنة',
    'profile': 'الملف الشخصي',
    'audit_logs': 'سجلات التدقيق',
    'loading_dashboard': 'جاري تحميل لوحة القيادة...',
    'statement_of_account': 'كشف حساب',
    'email_address': 'عنوان البريد الإلكتروني',
    'phone_number': 'رقم الهاتف',
    'roll_no': 'رقم الجلوس',
    'gender': 'الجنس',
    'parent_guardian': 'ولي الأمر / الوصي',
    'file_attachment_library': 'مكتبة الملفات المرفقة',
    'upload_document': 'تحميل مستند',
    'registry_empty': 'الموقع فارغ حالياً',
    'registry_empty_desc': 'قم بأرشفة شهادات الميلاد والهويات والعلامات بشكل آمن هنا.',
    'transaction_details': 'تفاصيل المعاملة',
    'original_amount': 'المبلغ الأصلي',
    'paid_so_far': 'المبلغ المدفوع حتى الآن',
    'remaining_balance': 'الرصيد المتبقي',
    'transaction_ledger': 'دفتر المعاملات',
    'amount_details': 'تفاصيل المبلغ',
    'balance_due': 'الرصيد المستحق',
    'paid_on': 'تاريخ الدفع',
    'due_by': 'يستحق في',
    'unknown_assessment': 'تقييم غير معروف',
    'graded': 'تم التقييم',
    'submitted': 'تم التسليم',
    'score': 'الدرجة',
    'date_of_birth': 'تاريخ الميلاد',
    'profile_security': 'الملف الشخصي والأمان',
    'general_preferences': 'الإعدادات العامة والتفضيلات',
    'roles_permissions': 'الأدوار والأذونات',
    'data_management': 'إدارة البيانات',
    'advanced_configurations': 'الإعدادات المتقدمة',
    'save_changes': 'حفظ التغييرات',
    'confirm': 'تأكيد',
    'action_confirmation': 'تأكيد الإجراء',
    'please_wait_moment': 'يرجى الانتظار للحظة...',
    'profile_settings_title': 'الملف الشخصي والإعدادات',
    'profile_settings_desc': 'إدارة إعدادات حسابك وتفضيلاتك.',
    'discard_changes_msg': 'تم تجاهل التغييرات',
    'profile_updated_success': 'تم تحديث الملف الشخصي بنجاح',
    'users_passwords': 'المستخدمون وكلمات المرور',
    'outstanding_balance_warning': 'مطلوب اتخاذ إجراء: لديك رصيد مستحق يحتاج إلى اهتمامك.',
    'assigned_plan': 'الخطة المعينة',
    'discount_scholarship': 'خصم / منحة دراسية',
    'total_invoiced': 'إجمالي الفواتير',
    'paid_in_full': 'تم السداد بالكامل',
    'financial_standing_ledger': 'الوضع المالي ونظرة عامة على السجل',
    'secure_checkout': 'الدفع الآمن',
    'paying_for': 'دفع لـ',
    'paying_total_outstanding': 'دفع إجمالي الرصيد المستحق',
    'total_to_pay': 'إجمالي المبلغ للدفع',
    'payment_amount_label': 'مبلغ الدفع ($)',
    'max_remaining': 'الحد الأقصى للمتبقي',
    'cardholder_name': 'اسم صاحب البطاقة',
    'cardholder_name_placeholder': 'مثال: جون دو',
    'card_number': 'رقم البطاقة',
    'expiry_date': 'تاريخ الانتهاء',
    'cvc': 'كود CVC',
    'pay_securely': 'ادفع بأمان',
    'invoice_details': 'تفاصيل الفاتورة',
    'viewing_complete_financial': 'عرض التفاصيل المالية الكاملة لهذه الفاتورة.',
    'term_description': 'الفترة / الوصف',
    'payment_transaction_history': 'تاريخ معاملات الدفع',
    'no_payment_transactions': 'لا توجد معاملات دفع مسجلة لهذه الفاتورة بعد.',
    'download_receipt': 'تحميل الإيصال',
    'downloading_receipt': 'جاري تحميل الإيصال',
    'receipt_for': 'إيصال لـ',
    'is_being_prepared': 'قيد التجهيز',
    'net_cash_flow': 'صافي التدفق النقدي',
    'revenue_efficiency': 'كفاءة الإيرادات',
    'total_receivables': 'إجمالي المستحقات',
    'operational_spend': 'الإنفاق التشغيلي',
    'this_month': 'هذا الشهر',
    'is_strictly_overdue': 'متأخر تماماً',
    'monthly_burn': 'الإنفاق الشهري',
    'all_dues': 'جميع المستحقات',
    'due_this_month': 'مستحق هذا الشهر',
    'due_next_month': 'مستحق الشهر القادم',
    'void_refund': 'إلغاء / استرداد',
    'paid_invoices': 'الفواتير المدفوعة',
    'student_fee_profile': 'ملف رسوم الطالب',
    'viewing_invoices_for': 'عرض سجل الفواتير المفصل لـ',
    'total_outstanding': 'إجمالي المستحقات',
    'recording_payment_for': 'تسجيل دفعة واردة لـ',
    'amount_to_pay': 'المبلغ للدفع',
    'select_student_search': 'بحث واختيار الطالب',
    'type_student_name_search': 'اكتب اسم الطالب للبحث...',
    'registration_fee': 'رسوم التسجيل',
    'transportation_fee': 'رسوم النقل',
    'uniform_fee': 'رسوم الزي المدرسي',
    'tuition_fee': 'الرسوم الدراسية',
    'books_materials': 'الكتب والمواد',
    'activities_fee': 'رسوم الأنشطة',
    'custom_invoice_title': 'عنوان فاتورة مخصص',
    'graduation_ceremony_fee': 'رسوم حفل التخرج مثلاً',
    'description_notes': 'الوصف / ملاحظات',
    'bus_fee_term_1': 'مثال: رسوم الحافلة - الفصل 1، زي مدرسي، رسوم التسجيل، إلخ.',
    'generate_new_fee_request': 'إنشاء طلب رسوم جديد للطالب.',
    'general_invoice_option': 'فاتورة عامة (غير مرتبطة بأي طالب)',
    'category_type': 'الفئة / النوع',
    'select_category_structure': 'اختر الفئة أو الهيكل...',
    'standard_categories': 'الفئات القياسية',
    'academic_grade_structures': 'هياكل الدرجات الأكاديمية',
    'other_custom_title': 'أخرى / عنوان مخصص...',
    'custom_invoice_title_label': 'عنوان فاتورة مخصص',
    'total_amount': 'المبلغ الإجمالي',
    'void': 'إلغاء',
    'grade_fee_structures': 'هياكل رسوم المراحل',
    'add_grade_structure': 'إضافة هيكل رسوم',
    'edit_grade_structure': 'تعديل هيكل الرسوم',
    'update_base_amount_grade': 'تحديث المبلغ الأساسي لهذه المرحلة.',
    'define_new_base_fee': 'تحديد هيكل رسوم أساسي جديد لمرحلة.',
    'grade_name': 'اسم المرحلة',
    'grade_1_placeholder': 'مثال: الصف الأول',
    'base_tuition_amount': 'المبلغ الأساسي للرسوم ($)',
    'update_structure': 'تحديث الهيكل',
    'add_structure': 'إضافة الهيكل',
    'delete_grade_structure': 'حذف هيكل الرسوم',
    'delete_grade_structure_confirm': 'هل أنت متأكد أنك تريد حذف هيكل الرسوم هذا؟ لن يؤثر هذا على الفواتير الحالية.',
    'expenses_management_desc': 'إدارة نفقات المدرسة ومدفوعات كشوف المرتبات',
    'record_expense': 'تسجيل نفقة',
    'no_expenses_recorded': 'لا توجد نفقات مسجلة بعد.',
    'maintenance': 'الصيانة',
    'supplies': 'المستلزمات',
    'utilities': 'المرافق',
    'miscellaneous': 'متنوع',
    'record': 'تسجيل',
    'my_profile': 'ملفي الشخصي',
    'access_credentials_desc': 'الوصول إلى بيانات الاعتماد والتفاصيل الأكاديمية والمستندات الخاصة بك.',
    'no_associated_profiles': 'لم يتم العثور على ملفات تعريف طلاب مرتبطة. يرجى الاتصال بالإدارة.',
    'directory': 'الدليل',
    'promotions': 'الترقيات',
    'bulk': 'عمليات جماعية',
    'bulk_assignment': 'تعيين جماعي',
    'history': 'السجل',
    'loading_profile': 'جاري تحميل الملف الشخصي...',
    'student_id_card_export': 'تصدير بطاقة هوية الطالب',
    'student_identity_card': 'بطاقة هوية الطالب',
    'smart_school_portal': 'بوابة المدرسة الذكية',
    'smart_school_management': 'إدارة المدرسة الذكية',
    'export_id_card': 'تصدير بطاقة الهوية',
    'valid': 'صالح',
    'birth_date': 'تاريخ الميلاد',
    'print_export': 'طباعة / تصدير',
    'grade_student': 'طالب في الصف',
    'gender_label': 'الجنس',
    'all_genders': 'جميع الأجناس',
    'all_years': 'جميع السنوات',
    'parent_guardian_search': 'البحث عن ولي أمر / وصي',
    'type_to_search_parent': 'اكتب للبحث عن ولي أمر...',
    'na': 'غير متاح',
    'student_promotions': 'ترقيات الطلاب',
    'student_promotions_desc': 'إدارة واعتماد ترقيات درجات الطلاب للعام الدراسي القادم.',
    'promote_selected': 'ترقية المختارين ({count})',
    'all_school': 'كل المدرسة',
    'by_grade': 'حسب المرحلة',
    'force_promotions_override': 'تجاوز الترقية الإجبارية',
    'current_grade': 'المرحلة الحالية',
    'exam_status': 'حالة الامتحان',
    'promote_to': 'الترقية إلى',
    'not_applicable': 'غير متاح',
    'not_yet_promoted': 'لم يتم الترقية بعد',
    'demoted': 'تم إنزال الدرجة',
    'passed': 'ناجح',
    'successfully_promoted': 'تمت ترقية {count} من الطلاب بنجاح',
    'failed_to_promote': 'فشلت ترقية الطلاب',
    'please_select_students_promote': 'يرجى اختيار الطلاب للترقية',
    'graduated': 'تخرج',
    'fee_assignment': 'تعيين الرسوم',
    'messaging': 'المراسلات',
    'registry_sync': 'مزامنة السجل',
    'select_fee_item': 'اختر بند الرسوم',
    'choose_fee': '-- اختر الرسم --',
    'payment_due_date': 'تاريخ استحقاق الدفع',
    'assign_to_count': 'تعيين لـ {count} من الطلاب',
    'subject_title': 'الموضوع / العنوان',
    'push_alert': 'تنبيه دفع',
    'email_alert': 'تنبيه بريد إلكتروني',
    'compose_message': 'اكتب الرسالة...',
    'send_to_count': 'إرسال إلى {count}',
    'registry_auth_sync': 'مزامنة مصادقة السجل',
    'registry_sync_desc': 'تضمن هذه الأداة أن جميع الطلاب المختارين لديهم بيانات اعتماد صالحة. استخدم هذا لإصلاح مشكلات تسجيل الدخول للطلاب المضافين يدويًا أو قبل عمليات التحديث الأخيرة للنظام.',
    'start_credential_sync': 'بدء مزامنة البيانات',
    'please_select_students_fee': 'يرجى اختيار الطلاب وبند الرسوم',
    'assigned_fee_to_count': 'تم تعيين {fee} لـ {count} من الطلاب',
    'failed_to_assign_fees': 'فشل تعيين الرسوم',
    'please_complete_all_fields': 'يرجى إكمال جميع الحقول',
    'message_sent_to_count': 'تم إرسال الرسالة لـ {count} من الطلاب',
    'failed_to_send_messages': 'فشل إرسال الرسائل',
    'please_select_students_sync': 'يرجى اختيار الطلاب للمزامنة',
    'failed_to_sync_auth': 'فشل مزامنة المصادقة',
    'automated_notification_footer': 'هذا إخطار تلقائي من نظام مدرستكم.',
    'fetching_registry': 'جاري جلب السجل...',
    'no_students_matched': 'لم يتطابق أي طلاب مع المعايير.',
    'selected_count_students_batch': 'تم اختيار {count} من الطلاب لعملية الدفعة.',
    'sync_count_students': 'مزامنة {count} من الطلاب',
    'student_id_label': 'رقم الطالب',
    'please_fix_errors_form': 'يرجى تصحيح الأخطاء في النموذج',
    'validation_error': 'خطأ في التحقق من البيانات',
    'student_updated_success': 'تم تحديث بيانات الطالب بنجاح',
    'failed_to_generate_student_id': 'فشل إنشاء رقم الطالب. يرجى المحاولة مرة أخرى.',
    'student_id_missing': 'رقم الطالب مفقود. يرجى إغلاق النموذج وإعادة فتحه.',
    'database_schema_error': 'خطأ في هيكل قاعدة البيانات',
    'registration_failed': 'فشل التسجيل',
    'student_registered_success': 'تم تسجيل الطالب بنجاح',
    'student_added_to_grade': 'تمت إضافة {name} إلى {grade}.',
    'failed_to_register_student': 'فشل تسجيل الطالب',
    'parent_email_address': 'البريد الإلكتروني لولي الأمر',
    'registration_finance_details': 'تفاصيل التسجيل والمالية',
    'date_of_joining': 'تاريخ الانضمام (التناسب)',
    'joining_date_desc': 'اتركه فارغاً لاستخدام بداية العام الدراسي.',
    'sibling_discount_scholarship': 'خصم الإخوة / منحة دراسية (%)',
    'discount_placeholder': 'مثال: 15 لخصم 15%',
    'fee_structure': 'هيكل الرسوم',
    'select_grade_fee_structure': 'اختر هيكل رسوم المرحلة',
    'select_fee_structure_option': 'اختر هيكل الرسوم',
    'custom_fees_amount': 'مبلغ رسوم مخصص',
    'manual_amount': 'المبلغ اليدوي ($)',
    'select_payment_structure': 'اختر هيكل الدفع',
    'term_payment_installment': 'دفع {count} فصول ({count} أقساط)',
    'confirm_delete_document': 'هل أنت متأكد أنك تريد حذف هذا المستند؟',
    'document_uploaded_success': 'تم تحميل المستند بنجاح',
    'document_deleted_success': 'تم حذف المستند بنجاح',
    'generating_pdf_invoice': 'جاري إنشاء فاتورة PDF...',
    'invoice_pdf_downloaded_success': 'تم تحميل فاتورة PDF بنجاح',
    'failed_download_pdf_invoice': 'فشل تحميل فاتورة PDF',
    'school_finance_department': 'قسم المالية بالمدرسة',
    'official_academic_tuition_bill': 'فاتورة الرسوم الدراسية الرسمية',
    'billed_to': 'فاتورة باسم',
    'important_dates': 'تواريخ مهمة',
    'general_tuition_installment': 'قسط الرسوم الدراسية العامة',
    'subtotal': 'المجموع الفرعي',
    'discounts': 'الخصومات',
    'amount_due_label': 'المبلغ المستحق',
    'thank_you_payment_contact': 'شكراً لتعاونكم. للاستفسارات ، يرجى الاتصال بمكتب المالية.',
    'generated_automatically_on': 'تم إنشاؤه تلقائياً في',
    'tapped_transaction_details_desc': 'يتم عرض تفاصيل المعاملة عند الضغط عليها',
    'classes_grading_ledgers': 'الصفوف وسجلات العلامات',
    'select_roster_desc': 'اختر قائمة تسجيل نشطة أدناه لتسجيل العلامات أو ربط التقييمات أو استخراج بطاقات التقارير المطبوعة.',
    'teacher_portal_mode': 'وضع بوابة المعلم',
    'capacity_label': 'السعة',
    'open_academic_ledger': 'فتح السجل الأكاديمي',
    'assigned_label': 'مُعين',
    'observe_only': 'للمراقبة فقط',
    'no_classes_configured': 'لم يتم تكوين أي صفوف بعد',
    'roster_database': 'قاعدة بيانات القوائم',
    'roster_database_desc': 'تقديم درجات الطلاب الفردية ، وإدارة أوراق المواد ، وتصدير مصفوفات الدرجات.',
    'monthly_exams': 'الامتحانات الشهرية',
    'publish_term': 'نشر الفصل',
    'unpublish_term': 'إلغاء نشر الفصل',
    'export_all_reports': 'تصدير كافة التقارير',
    'by_student': 'حسب الطالب',
    'by_subject': 'حسب المادة',
    'search_academic_courses': 'البحث في المواد الأكاديمية...',
    'roster_name': 'اسم القائمة',
    'academic_state': 'الحالة الأكاديمية',
    'published_label': 'منشور',
    'confidential_label': 'سري',
    'preview_print': 'معاينة الطباعة',
    'grade_entry': 'إدخال الدرجات',
    'subject_scheme': 'مخطط المادة',
    'assigned_instructor': 'المعلم المعين',
    'available_admin_access': 'متاح (وصول المشرف)',
    'grade_all_students': 'رصد درجات جميع الطلاب',
    'roll_label': 'رقم',
    'teacher_grading_notice': 'بصفتك معلماً ، يمكنك فقط تعديل درجات المواد المسندة إليك في جدول الحصص. وتظهر المواد المقفلة برمز قفل.',
    'admin_grading_notice': 'بصفتك مديراً ، لديك كامل الصلاحية للتعديل على جميع المواد في السجل .',
    'assigned_to_you': 'مسند إليك',
    'staff_assigned': 'تم تعيين معلم',
    'lock_label': 'قفل',
    'score_placeholder': 'الدرجة',
    'score_exceeds_error': 'الدرجة تتجاوز المقياس! الحد الأقصى هو',
    'public_comments_placeholder': 'ملاحظات بطاقة التقرير العامة...',
    'internal_remarks_placeholder': 'ملاحظات داخلية (اختياري)...',
    'link_exam': 'ربط الامتحان',
    'submit_assessment_scores': 'تقديم درجات التقييم',
    'grading_sheet': 'ورقة الدرجات',
    'no_students_registered': 'لا توجد أدلة طلابية نشطة مسجلة داخل',
    'feedback_remarks_placeholder': 'الملاحظات / التغذية الراجعة...',
    'update_all_scores_notice': 'سيقوم هذا بتحديث درجات {subjectName} لجميع الصفوف المسجلة في نفس الوقت.',
    'update_courses_spreadsheet': 'تحديث جدول المواد',
    'final_percentage_label': 'النسبة النهائية %',
    'final_grade_label': 'التقدير النهائي',
    'final_rank_label': 'الترتيب النهائي',
    'no_records_found': 'لم يتم العثور على سجلات للطلاب',
    'no_student_credentials_desc': 'لا توجد حسابات طلاب مرتبطة حالياً ببيانات اعتمادك.',
    'document_printing_desk': 'مكتب طباعة المستندات',
    'printing_desk_desc': 'تبديل التخطيطات وتكوين خيارات الطابعة.',
    'single_period_card': 'بطاقة فترة واحدة',
    'annual_progress_report': 'تقرير التقدم السنوي',
    'print_save_pdf': 'طباعة / حفظ PDF',
    'close_drawer': 'إغلاق الدرج',
    'awaiting': 'قيد الانتظار',
    'consistently_responsive_feedback': 'يستجيب باستمرار في التدريبات التعليمية الروتينية.',
    'compiling': 'جاري التجميع...',
    '1st_term': 'الفصل الدراسي الأول',
    '2nd_term': 'الفصل الدراسي الثاني',
    'final_exam': 'الامتحان النهائي',
    'class_rank': 'الترتيب في الصف',
    'aggregating_records': 'تجميع فهارس السجلات...',
    'official_academic_performance': 'المؤهلات الرسمية للأداء الأكاديمي',
    'student_label': 'الطالب',
    'roll_no_label': 'رقم القيد',
    'academic_term_label': 'الفصل الأكاديمي',
    'course_catalog': 'فهرس المواد',
    'max_scale': 'المقياس الأقصى',
    'score_obtained': 'الدرجة المحصلة',
    'letter_grade': 'التقدير بالحروف',
    'instructor_feedback': 'ملاحظات المعلم',
    'admin_eval_legend': 'أسطورة مؤشر التقييم الإداري',
    'academic_attendance': 'الحضور الأكاديمي',
    'total_days': 'إجمالي الأيام',
    'attended': 'حضر',
    'absent_label': 'غاب',
    'calculating_records': 'حساب سجلات القيد...',
    'performance_standing': 'مستوى الأداء',
    'teacher_endorsement': 'تزكية المعلم',
    'admin_registrar': 'المسجل الإداري',
    'annual_progress_credentials': 'مؤهلات التقدم والأداء السنوي',
    'year_label': 'العام',
    'obtained_label': 'المحصل',
    'mo_avg': 'متوسط الشهر',
    'performance_eval_summary': 'ملخص تقييم الأداء',
    'overall_term_percentile': 'النسبة المئوية للفصل الإجمالي',
    'class_standing': 'الترتيب في الصف',
    'school_attendance': 'الحضور المدرسي',
    'registrar_credentials': 'بيانات المسجل',
    'registrar_cert_text': 'هذا يشهد بأن {name} قد أتم متطلبات مناهج الصف المقابلة بتسجيل نشط صحيح.',
    'registrar_signature': 'توقيع المسجل',
    'principal_signature': 'توقيع المدير',
    'return_to_dashboard': 'العودة إلى لوحة القيادة',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    const savedLang = localStorage.getItem('language') as Language;
    if (savedLang && (savedLang === 'en' || savedLang === 'ar')) {
      // eslint-disable-next-line react-hooks/set-state-in-effect
      setLanguageState(savedLang);
    }
    setMounted(true);
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  useEffect(() => {
    if (mounted) {
      document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
      document.documentElement.lang = language;
    }
  }, [language, mounted]);

  // If we don't want to show wrong layout briefly, we can just render nothing until mounted
  // But wait, returning children directly with default EN is fine, if we use suppressHydrationWarning where we use language for dir.
  // We'll just return it. The hydration mismatch is because `language` string changes. Let's just suppress hydration warning in page.tsx or return null until mounted if we must, but returning children is standard.


  const t = (key: string) => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  const isRTL = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
